// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ads_pln.proto

#ifndef PROTOBUF_INCLUDED_ads_5fpln_2eproto
#define PROTOBUF_INCLUDED_ads_5fpln_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ads_com.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ads_5fpln_2eproto 

namespace protobuf_ads_5fpln_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ads_5fpln_2eproto
namespace ads_pln {
class PLN_Outputs;
class PLN_OutputsDefaultTypeInternal;
extern PLN_OutputsDefaultTypeInternal _PLN_Outputs_default_instance_;
}  // namespace ads_pln
namespace google {
namespace protobuf {
template<> ::ads_pln::PLN_Outputs* Arena::CreateMaybeMessage<::ads_pln::PLN_Outputs>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ads_pln {

// ===================================================================

class PLN_Outputs : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ads_pln.PLN_Outputs) */ {
 public:
  PLN_Outputs();
  virtual ~PLN_Outputs();

  PLN_Outputs(const PLN_Outputs& from);

  inline PLN_Outputs& operator=(const PLN_Outputs& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PLN_Outputs(PLN_Outputs&& from) noexcept
    : PLN_Outputs() {
    *this = ::std::move(from);
  }

  inline PLN_Outputs& operator=(PLN_Outputs&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PLN_Outputs& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PLN_Outputs* internal_default_instance() {
    return reinterpret_cast<const PLN_Outputs*>(
               &_PLN_Outputs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PLN_Outputs* other);
  friend void swap(PLN_Outputs& a, PLN_Outputs& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PLN_Outputs* New() const final {
    return CreateMaybeMessage<PLN_Outputs>(NULL);
  }

  PLN_Outputs* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PLN_Outputs>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PLN_Outputs& from);
  void MergeFrom(const PLN_Outputs& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PLN_Outputs* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .ads_common.B_ACCObjVldLv2 PLN_OUT_CODP_bus_ACCObjVldLv2 = 25;
  bool has_pln_out_codp_bus_accobjvldlv2() const;
  void clear_pln_out_codp_bus_accobjvldlv2();
  static const int kPLNOUTCODPBusACCObjVldLv2FieldNumber = 25;
  private:
  const ::ads_common::B_ACCObjVldLv2& _internal_pln_out_codp_bus_accobjvldlv2() const;
  public:
  const ::ads_common::B_ACCObjVldLv2& pln_out_codp_bus_accobjvldlv2() const;
  ::ads_common::B_ACCObjVldLv2* release_pln_out_codp_bus_accobjvldlv2();
  ::ads_common::B_ACCObjVldLv2* mutable_pln_out_codp_bus_accobjvldlv2();
  void set_allocated_pln_out_codp_bus_accobjvldlv2(::ads_common::B_ACCObjVldLv2* pln_out_codp_bus_accobjvldlv2);

  // .ads_common.B_ACCObj03_st PLN_OUT_DA_IN_bus_ACCObj03 = 26;
  bool has_pln_out_da_in_bus_accobj03() const;
  void clear_pln_out_da_in_bus_accobj03();
  static const int kPLNOUTDAINBusACCObj03FieldNumber = 26;
  private:
  const ::ads_common::B_ACCObj03_st& _internal_pln_out_da_in_bus_accobj03() const;
  public:
  const ::ads_common::B_ACCObj03_st& pln_out_da_in_bus_accobj03() const;
  ::ads_common::B_ACCObj03_st* release_pln_out_da_in_bus_accobj03();
  ::ads_common::B_ACCObj03_st* mutable_pln_out_da_in_bus_accobj03();
  void set_allocated_pln_out_da_in_bus_accobj03(::ads_common::B_ACCObj03_st* pln_out_da_in_bus_accobj03);

  // .ads_common.B_ACCObj04_st PLN_OUT_DA_IN_bus_ACCObj04 = 27;
  bool has_pln_out_da_in_bus_accobj04() const;
  void clear_pln_out_da_in_bus_accobj04();
  static const int kPLNOUTDAINBusACCObj04FieldNumber = 27;
  private:
  const ::ads_common::B_ACCObj04_st& _internal_pln_out_da_in_bus_accobj04() const;
  public:
  const ::ads_common::B_ACCObj04_st& pln_out_da_in_bus_accobj04() const;
  ::ads_common::B_ACCObj04_st* release_pln_out_da_in_bus_accobj04();
  ::ads_common::B_ACCObj04_st* mutable_pln_out_da_in_bus_accobj04();
  void set_allocated_pln_out_da_in_bus_accobj04(::ads_common::B_ACCObj04_st* pln_out_da_in_bus_accobj04);

  // .ads_common.B_ACCStnObj03_st PLN_OUT_DA_IN_bus_ACCStnObj03 = 28;
  bool has_pln_out_da_in_bus_accstnobj03() const;
  void clear_pln_out_da_in_bus_accstnobj03();
  static const int kPLNOUTDAINBusACCStnObj03FieldNumber = 28;
  private:
  const ::ads_common::B_ACCStnObj03_st& _internal_pln_out_da_in_bus_accstnobj03() const;
  public:
  const ::ads_common::B_ACCStnObj03_st& pln_out_da_in_bus_accstnobj03() const;
  ::ads_common::B_ACCStnObj03_st* release_pln_out_da_in_bus_accstnobj03();
  ::ads_common::B_ACCStnObj03_st* mutable_pln_out_da_in_bus_accstnobj03();
  void set_allocated_pln_out_da_in_bus_accstnobj03(::ads_common::B_ACCStnObj03_st* pln_out_da_in_bus_accstnobj03);

  // .ads_common.B_ACCStnObj04_st PLN_OUT_DA_IN_bus_ACCStnObj04 = 29;
  bool has_pln_out_da_in_bus_accstnobj04() const;
  void clear_pln_out_da_in_bus_accstnobj04();
  static const int kPLNOUTDAINBusACCStnObj04FieldNumber = 29;
  private:
  const ::ads_common::B_ACCStnObj04_st& _internal_pln_out_da_in_bus_accstnobj04() const;
  public:
  const ::ads_common::B_ACCStnObj04_st& pln_out_da_in_bus_accstnobj04() const;
  ::ads_common::B_ACCStnObj04_st* release_pln_out_da_in_bus_accstnobj04();
  ::ads_common::B_ACCStnObj04_st* mutable_pln_out_da_in_bus_accstnobj04();
  void set_allocated_pln_out_da_in_bus_accstnobj04(::ads_common::B_ACCStnObj04_st* pln_out_da_in_bus_accstnobj04);

  // .ads_common.B_ACCObjVldRaw PLN_OUT_CODP_bus_ACCObjVldRaw = 30;
  bool has_pln_out_codp_bus_accobjvldraw() const;
  void clear_pln_out_codp_bus_accobjvldraw();
  static const int kPLNOUTCODPBusACCObjVldRawFieldNumber = 30;
  private:
  const ::ads_common::B_ACCObjVldRaw& _internal_pln_out_codp_bus_accobjvldraw() const;
  public:
  const ::ads_common::B_ACCObjVldRaw& pln_out_codp_bus_accobjvldraw() const;
  ::ads_common::B_ACCObjVldRaw* release_pln_out_codp_bus_accobjvldraw();
  ::ads_common::B_ACCObjVldRaw* mutable_pln_out_codp_bus_accobjvldraw();
  void set_allocated_pln_out_codp_bus_accobjvldraw(::ads_common::B_ACCObjVldRaw* pln_out_codp_bus_accobjvldraw);

  // .ads_common.HafLonTrajParam PLN_OUT_bus_HafLonTrajParam = 58;
  bool has_pln_out_bus_haflontrajparam() const;
  void clear_pln_out_bus_haflontrajparam();
  static const int kPLNOUTBusHafLonTrajParamFieldNumber = 58;
  private:
  const ::ads_common::HafLonTrajParam& _internal_pln_out_bus_haflontrajparam() const;
  public:
  const ::ads_common::HafLonTrajParam& pln_out_bus_haflontrajparam() const;
  ::ads_common::HafLonTrajParam* release_pln_out_bus_haflontrajparam();
  ::ads_common::HafLonTrajParam* mutable_pln_out_bus_haflontrajparam();
  void set_allocated_pln_out_bus_haflontrajparam(::ads_common::HafLonTrajParam* pln_out_bus_haflontrajparam);

  // float PLN_OUT_ACC_r_CLDPLaneRadius_sg = 2;
  void clear_pln_out_acc_r_cldplaneradius_sg();
  static const int kPLNOUTACCRCLDPLaneRadiusSgFieldNumber = 2;
  float pln_out_acc_r_cldplaneradius_sg() const;
  void set_pln_out_acc_r_cldplaneradius_sg(float value);

  // float PLN_OUT_cv_CLDPDynTrajParA2_sg = 3;
  void clear_pln_out_cv_cldpdyntrajpara2_sg();
  static const int kPLNOUTCvCLDPDynTrajParA2SgFieldNumber = 3;
  float pln_out_cv_cldpdyntrajpara2_sg() const;
  void set_pln_out_cv_cldpdyntrajpara2_sg(float value);

  // float PLN_OUT_cvr_CLDPDynTrajParA3_sg = 4;
  void clear_pln_out_cvr_cldpdyntrajpara3_sg();
  static const int kPLNOUTCvrCLDPDynTrajParA3SgFieldNumber = 4;
  float pln_out_cvr_cldpdyntrajpara3_sg() const;
  void set_pln_out_cvr_cldpdyntrajpara3_sg(float value);

  // bool PLN_OUT_ACC_is_CLDPLaneErr_bl = 1;
  void clear_pln_out_acc_is_cldplaneerr_bl();
  static const int kPLNOUTACCIsCLDPLaneErrBlFieldNumber = 1;
  bool pln_out_acc_is_cldplaneerr_bl() const;
  void set_pln_out_acc_is_cldplaneerr_bl(bool value);

  // bool PLN_OUT_ACC_is_CLDPEmgrLneChgRAW_bl = 5;
  void clear_pln_out_acc_is_cldpemgrlnechgraw_bl();
  static const int kPLNOUTACCIsCLDPEmgrLneChgRAWBlFieldNumber = 5;
  bool pln_out_acc_is_cldpemgrlnechgraw_bl() const;
  void set_pln_out_acc_is_cldpemgrlnechgraw_bl(bool value);

  // bool PLN_OUT_ACC_is_CLDPEmgrLneChg_bl = 6;
  void clear_pln_out_acc_is_cldpemgrlnechg_bl();
  static const int kPLNOUTACCIsCLDPEmgrLneChgBlFieldNumber = 6;
  bool pln_out_acc_is_cldpemgrlnechg_bl() const;
  void set_pln_out_acc_is_cldpemgrlnechg_bl(bool value);

  // bool PLN_OUT_is_CLDPLftLneCrosBgn_bl = 7;
  void clear_pln_out_is_cldplftlnecrosbgn_bl();
  static const int kPLNOUTIsCLDPLftLneCrosBgnBlFieldNumber = 7;
  bool pln_out_is_cldplftlnecrosbgn_bl() const;
  void set_pln_out_is_cldplftlnecrosbgn_bl(bool value);

  // bool PLN_OUT_is_CLDPRgtLneCrosBgn_bl = 8;
  void clear_pln_out_is_cldprgtlnecrosbgn_bl();
  static const int kPLNOUTIsCLDPRgtLneCrosBgnBlFieldNumber = 8;
  bool pln_out_is_cldprgtlnecrosbgn_bl() const;
  void set_pln_out_is_cldprgtlnecrosbgn_bl(bool value);

  // bool PLN_OUT_is_CLDPLftLneCrosEnd_bl = 9;
  void clear_pln_out_is_cldplftlnecrosend_bl();
  static const int kPLNOUTIsCLDPLftLneCrosEndBlFieldNumber = 9;
  bool pln_out_is_cldplftlnecrosend_bl() const;
  void set_pln_out_is_cldplftlnecrosend_bl(bool value);

  // bool PLN_OUT_is_CLDPRgtLneCrosEnd_bl = 10;
  void clear_pln_out_is_cldprgtlnecrosend_bl();
  static const int kPLNOUTIsCLDPRgtLneCrosEndBlFieldNumber = 10;
  bool pln_out_is_cldprgtlnecrosend_bl() const;
  void set_pln_out_is_cldprgtlnecrosend_bl(bool value);

  // bool PLN_OUT_is_CODPFoloTgtExist_bl = 11;
  void clear_pln_out_is_codpfolotgtexist_bl();
  static const int kPLNOUTIsCODPFoloTgtExistBlFieldNumber = 11;
  bool pln_out_is_codpfolotgtexist_bl() const;
  void set_pln_out_is_codpfolotgtexist_bl(bool value);

  // float PLN_OUT_d_CODPFMRdrLatDist_sg = 12;
  void clear_pln_out_d_codpfmrdrlatdist_sg();
  static const int kPLNOUTDCODPFMRdrLatDistSgFieldNumber = 12;
  float pln_out_d_codpfmrdrlatdist_sg() const;
  void set_pln_out_d_codpfmrdrlatdist_sg(float value);

  // float PLN_OUT_v_CODPACCLongtRltvSpd_sg = 13;
  void clear_pln_out_v_codpacclongtrltvspd_sg();
  static const int kPLNOUTVCODPACCLongtRltvSpdSgFieldNumber = 13;
  float pln_out_v_codpacclongtrltvspd_sg() const;
  void set_pln_out_v_codpacclongtrltvspd_sg(float value);

  // float PLN_OUT_v_CODPACCHdVehSpd_sg = 14;
  void clear_pln_out_v_codpacchdvehspd_sg();
  static const int kPLNOUTVCODPACCHdVehSpdSgFieldNumber = 14;
  float pln_out_v_codpacchdvehspd_sg() const;
  void set_pln_out_v_codpacchdvehspd_sg(float value);

  // float PLN_OUT_d_CODPACCFMRdrLongtDist_sg = 15;
  void clear_pln_out_d_codpaccfmrdrlongtdist_sg();
  static const int kPLNOUTDCODPACCFMRdrLongtDistSgFieldNumber = 15;
  float pln_out_d_codpaccfmrdrlongtdist_sg() const;
  void set_pln_out_d_codpaccfmrdrlongtdist_sg(float value);

  // sint32 PLN_OUT_indx_CODPACCTgtID_u8 = 16;
  void clear_pln_out_indx_codpacctgtid_u8();
  static const int kPLNOUTIndxCODPACCTgtIDU8FieldNumber = 16;
  ::google::protobuf::int32 pln_out_indx_codpacctgtid_u8() const;
  void set_pln_out_indx_codpacctgtid_u8(::google::protobuf::int32 value);

  // float PLN_OUT_v_ACCHdVehLatSpd_sg = 17;
  void clear_pln_out_v_acchdvehlatspd_sg();
  static const int kPLNOUTVACCHdVehLatSpdSgFieldNumber = 17;
  float pln_out_v_acchdvehlatspd_sg() const;
  void set_pln_out_v_acchdvehlatspd_sg(float value);

  // float PLN_OUT_a_ACCHdVehLgtAcc_sg = 18;
  void clear_pln_out_a_acchdvehlgtacc_sg();
  static const int kPLNOUTAACCHdVehLgtAccSgFieldNumber = 18;
  float pln_out_a_acchdvehlgtacc_sg() const;
  void set_pln_out_a_acchdvehlgtacc_sg(float value);

  // float PLN_OUT_a_ACCHdVehLatAcc_sg = 19;
  void clear_pln_out_a_acchdvehlatacc_sg();
  static const int kPLNOUTAACCHdVehLatAccSgFieldNumber = 19;
  float pln_out_a_acchdvehlatacc_sg() const;
  void set_pln_out_a_acchdvehlatacc_sg(float value);

  // float PLN_OUT_d_ACCHdVehWidth_sg = 20;
  void clear_pln_out_d_acchdvehwidth_sg();
  static const int kPLNOUTDACCHdVehWidthSgFieldNumber = 20;
  float pln_out_d_acchdvehwidth_sg() const;
  void set_pln_out_d_acchdvehwidth_sg(float value);

  // .ads_common.eCSNR_ACCObjSnsr PLN_OUT_indx_ACCObjSnsr_en = 21;
  void clear_pln_out_indx_accobjsnsr_en();
  static const int kPLNOUTIndxACCObjSnsrEnFieldNumber = 21;
  ::ads_common::eCSNR_ACCObjSnsr pln_out_indx_accobjsnsr_en() const;
  void set_pln_out_indx_accobjsnsr_en(::ads_common::eCSNR_ACCObjSnsr value);

  // .ads_common.eCTRK_ACCObjTrackSts PLN_OUT_indx_ACCObjTrackSts_en = 22;
  void clear_pln_out_indx_accobjtracksts_en();
  static const int kPLNOUTIndxACCObjTrackStsEnFieldNumber = 22;
  ::ads_common::eCTRK_ACCObjTrackSts pln_out_indx_accobjtracksts_en() const;
  void set_pln_out_indx_accobjtracksts_en(::ads_common::eCTRK_ACCObjTrackSts value);

  // .ads_common.eCMV_ACCObjMvSts PLN_OUT_indx_ACCObjMvSts_en = 23;
  void clear_pln_out_indx_accobjmvsts_en();
  static const int kPLNOUTIndxACCObjMvStsEnFieldNumber = 23;
  ::ads_common::eCMV_ACCObjMvSts pln_out_indx_accobjmvsts_en() const;
  void set_pln_out_indx_accobjmvsts_en(::ads_common::eCMV_ACCObjMvSts value);

  // .ads_common.eCLS_ACCObjClass PLN_OUT_indx_ACCObjClass_en = 24;
  void clear_pln_out_indx_accobjclass_en();
  static const int kPLNOUTIndxACCObjClassEnFieldNumber = 24;
  ::ads_common::eCLS_ACCObjClass pln_out_indx_accobjclass_en() const;
  void set_pln_out_indx_accobjclass_en(::ads_common::eCLS_ACCObjClass value);

  // bool PLN_OUT_DFIn_is_MovObjPrtctWrn_bl = 31;
  void clear_pln_out_dfin_is_movobjprtctwrn_bl();
  static const int kPLNOUTDFInIsMovObjPrtctWrnBlFieldNumber = 31;
  bool pln_out_dfin_is_movobjprtctwrn_bl() const;
  void set_pln_out_dfin_is_movobjprtctwrn_bl(bool value);

  // bool PLN_OUT_DFIn_is_StnObjPrtctWrn_bl = 32;
  void clear_pln_out_dfin_is_stnobjprtctwrn_bl();
  static const int kPLNOUTDFInIsStnObjPrtctWrnBlFieldNumber = 32;
  bool pln_out_dfin_is_stnobjprtctwrn_bl() const;
  void set_pln_out_dfin_is_stnobjprtctwrn_bl(bool value);

  // bool PLN_OUT_DFIn_is_CODPPedWrn_bl = 33;
  void clear_pln_out_dfin_is_codppedwrn_bl();
  static const int kPLNOUTDFInIsCODPPedWrnBlFieldNumber = 33;
  bool pln_out_dfin_is_codppedwrn_bl() const;
  void set_pln_out_dfin_is_codppedwrn_bl(bool value);

  // bool PLN_OUT_ACC_is_VldMovObjTurnDscrd_bl = 36;
  void clear_pln_out_acc_is_vldmovobjturndscrd_bl();
  static const int kPLNOUTACCIsVldMovObjTurnDscrdBlFieldNumber = 36;
  bool pln_out_acc_is_vldmovobjturndscrd_bl() const;
  void set_pln_out_acc_is_vldmovobjturndscrd_bl(bool value);

  // float PLN_OUT_DFIn_t_ACCMovTTC_sg = 34;
  void clear_pln_out_dfin_t_accmovttc_sg();
  static const int kPLNOUTDFInTACCMovTTCSgFieldNumber = 34;
  float pln_out_dfin_t_accmovttc_sg() const;
  void set_pln_out_dfin_t_accmovttc_sg(float value);

  // float PLN_OUT_DFIn_t_ACCStnTTC_sg = 35;
  void clear_pln_out_dfin_t_accstnttc_sg();
  static const int kPLNOUTDFInTACCStnTTCSgFieldNumber = 35;
  float pln_out_dfin_t_accstnttc_sg() const;
  void set_pln_out_dfin_t_accstnttc_sg(float value);

  // bool PLN_OUT_VldMovObjDscrdExit_bl = 37;
  void clear_pln_out_vldmovobjdscrdexit_bl();
  static const int kPLNOUTVldMovObjDscrdExitBlFieldNumber = 37;
  bool pln_out_vldmovobjdscrdexit_bl() const;
  void set_pln_out_vldmovobjdscrdexit_bl(bool value);

  // bool PLN_OUT_ACC_is_VldStnObjTurnDscrd_bl = 38;
  void clear_pln_out_acc_is_vldstnobjturndscrd_bl();
  static const int kPLNOUTACCIsVldStnObjTurnDscrdBlFieldNumber = 38;
  bool pln_out_acc_is_vldstnobjturndscrd_bl() const;
  void set_pln_out_acc_is_vldstnobjturndscrd_bl(bool value);

  // bool PLN_OUT_ACC_is_VldStnObjDscrdExit_bl = 39;
  void clear_pln_out_acc_is_vldstnobjdscrdexit_bl();
  static const int kPLNOUTACCIsVldStnObjDscrdExitBlFieldNumber = 39;
  bool pln_out_acc_is_vldstnobjdscrdexit_bl() const;
  void set_pln_out_acc_is_vldstnobjdscrdexit_bl(bool value);

  // bool PLN_OUT_DFIn_is_CODPObjNSL_bl = 40;
  void clear_pln_out_dfin_is_codpobjnsl_bl();
  static const int kPLNOUTDFInIsCODPObjNSLBlFieldNumber = 40;
  bool pln_out_dfin_is_codpobjnsl_bl() const;
  void set_pln_out_dfin_is_codpobjnsl_bl(bool value);

  // bool PLN_OUT_DFIn_is_TgtLgtDisNdF_bl = 41;
  void clear_pln_out_dfin_is_tgtlgtdisndf_bl();
  static const int kPLNOUTDFInIsTgtLgtDisNdFBlFieldNumber = 41;
  bool pln_out_dfin_is_tgtlgtdisndf_bl() const;
  void set_pln_out_dfin_is_tgtlgtdisndf_bl(bool value);

  // bool PLN_OUT_DFIn_is_CODPLgtFtEX_bl = 42;
  void clear_pln_out_dfin_is_codplgtftex_bl();
  static const int kPLNOUTDFInIsCODPLgtFtEXBlFieldNumber = 42;
  bool pln_out_dfin_is_codplgtftex_bl() const;
  void set_pln_out_dfin_is_codplgtftex_bl(bool value);

  // bool PLN_OUT_ACC_is_ACC03CutinSure_bl = 43;
  void clear_pln_out_acc_is_acc03cutinsure_bl();
  static const int kPLNOUTACCIsACC03CutinSureBlFieldNumber = 43;
  bool pln_out_acc_is_acc03cutinsure_bl() const;
  void set_pln_out_acc_is_acc03cutinsure_bl(bool value);

  // bool PLN_OUT_ACC_is_ACC04CutinSure_bl = 44;
  void clear_pln_out_acc_is_acc04cutinsure_bl();
  static const int kPLNOUTACCIsACC04CutinSureBlFieldNumber = 44;
  bool pln_out_acc_is_acc04cutinsure_bl() const;
  void set_pln_out_acc_is_acc04cutinsure_bl(bool value);

  // float PLN_OUT_K_DesTrajC0_sg = 45;
  void clear_pln_out_k_destrajc0_sg();
  static const int kPLNOUTKDesTrajC0SgFieldNumber = 45;
  float pln_out_k_destrajc0_sg() const;
  void set_pln_out_k_destrajc0_sg(float value);

  // float PLN_OUT_K_DesTrajC1_sg = 46;
  void clear_pln_out_k_destrajc1_sg();
  static const int kPLNOUTKDesTrajC1SgFieldNumber = 46;
  float pln_out_k_destrajc1_sg() const;
  void set_pln_out_k_destrajc1_sg(float value);

  // float PLN_OUT_K_DesTrajC2_sg = 47;
  void clear_pln_out_k_destrajc2_sg();
  static const int kPLNOUTKDesTrajC2SgFieldNumber = 47;
  float pln_out_k_destrajc2_sg() const;
  void set_pln_out_k_destrajc2_sg(float value);

  // float PLN_OUT_K_DesTrajC3_sg = 48;
  void clear_pln_out_k_destrajc3_sg();
  static const int kPLNOUTKDesTrajC3SgFieldNumber = 48;
  float pln_out_k_destrajc3_sg() const;
  void set_pln_out_k_destrajc3_sg(float value);

  // float PLN_OUT_K_DesTrajC4_sg = 49;
  void clear_pln_out_k_destrajc4_sg();
  static const int kPLNOUTKDesTrajC4SgFieldNumber = 49;
  float pln_out_k_destrajc4_sg() const;
  void set_pln_out_k_destrajc4_sg(float value);

  // float PLN_OUT_K_DesTrajC5_sg = 50;
  void clear_pln_out_k_destrajc5_sg();
  static const int kPLNOUTKDesTrajC5SgFieldNumber = 50;
  float pln_out_k_destrajc5_sg() const;
  void set_pln_out_k_destrajc5_sg(float value);

  // float PLN_OUT_d_DesTrajSend_sg = 51;
  void clear_pln_out_d_destrajsend_sg();
  static const int kPLNOUTDDesTrajSendSgFieldNumber = 51;
  float pln_out_d_destrajsend_sg() const;
  void set_pln_out_d_destrajsend_sg(float value);

  // float PLN_OUT_d_DesTrajSego_sg = 52;
  void clear_pln_out_d_destrajsego_sg();
  static const int kPLNOUTDDesTrajSegoSgFieldNumber = 52;
  float pln_out_d_destrajsego_sg() const;
  void set_pln_out_d_destrajsego_sg(float value);

  // .ads_common.eRPL_RePlanLevel PLN_OUT_sts_ReplnLvl_eRPL = 53;
  void clear_pln_out_sts_replnlvl_erpl();
  static const int kPLNOUTStsReplnLvlERPLFieldNumber = 53;
  ::ads_common::eRPL_RePlanLevel pln_out_sts_replnlvl_erpl() const;
  void set_pln_out_sts_replnlvl_erpl(::ads_common::eRPL_RePlanLevel value);

  // float PLN_OUT_m_STrajError_sg = 54;
  void clear_pln_out_m_strajerror_sg();
  static const int kPLNOUTMSTrajErrorSgFieldNumber = 54;
  float pln_out_m_strajerror_sg() const;
  void set_pln_out_m_strajerror_sg(float value);

  // float PLN_OUT_v_SpdTrajCmd_sg = 55;
  void clear_pln_out_v_spdtrajcmd_sg();
  static const int kPLNOUTVSpdTrajCmdSgFieldNumber = 55;
  float pln_out_v_spdtrajcmd_sg() const;
  void set_pln_out_v_spdtrajcmd_sg(float value);

  // float PLN_OUT_a_AccTrajCmd_sg = 56;
  void clear_pln_out_a_acctrajcmd_sg();
  static const int kPLNOUTAAccTrajCmdSgFieldNumber = 56;
  float pln_out_a_acctrajcmd_sg() const;
  void set_pln_out_a_acctrajcmd_sg(float value);

  // sint32 PLN_OUT_is_LongTraj_Replan_Level = 57;
  void clear_pln_out_is_longtraj_replan_level();
  static const int kPLNOUTIsLongTrajReplanLevelFieldNumber = 57;
  ::google::protobuf::int32 pln_out_is_longtraj_replan_level() const;
  void set_pln_out_is_longtraj_replan_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ads_pln.PLN_Outputs)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::ads_common::B_ACCObjVldLv2* pln_out_codp_bus_accobjvldlv2_;
  ::ads_common::B_ACCObj03_st* pln_out_da_in_bus_accobj03_;
  ::ads_common::B_ACCObj04_st* pln_out_da_in_bus_accobj04_;
  ::ads_common::B_ACCStnObj03_st* pln_out_da_in_bus_accstnobj03_;
  ::ads_common::B_ACCStnObj04_st* pln_out_da_in_bus_accstnobj04_;
  ::ads_common::B_ACCObjVldRaw* pln_out_codp_bus_accobjvldraw_;
  ::ads_common::HafLonTrajParam* pln_out_bus_haflontrajparam_;
  float pln_out_acc_r_cldplaneradius_sg_;
  float pln_out_cv_cldpdyntrajpara2_sg_;
  float pln_out_cvr_cldpdyntrajpara3_sg_;
  bool pln_out_acc_is_cldplaneerr_bl_;
  bool pln_out_acc_is_cldpemgrlnechgraw_bl_;
  bool pln_out_acc_is_cldpemgrlnechg_bl_;
  bool pln_out_is_cldplftlnecrosbgn_bl_;
  bool pln_out_is_cldprgtlnecrosbgn_bl_;
  bool pln_out_is_cldplftlnecrosend_bl_;
  bool pln_out_is_cldprgtlnecrosend_bl_;
  bool pln_out_is_codpfolotgtexist_bl_;
  float pln_out_d_codpfmrdrlatdist_sg_;
  float pln_out_v_codpacclongtrltvspd_sg_;
  float pln_out_v_codpacchdvehspd_sg_;
  float pln_out_d_codpaccfmrdrlongtdist_sg_;
  ::google::protobuf::int32 pln_out_indx_codpacctgtid_u8_;
  float pln_out_v_acchdvehlatspd_sg_;
  float pln_out_a_acchdvehlgtacc_sg_;
  float pln_out_a_acchdvehlatacc_sg_;
  float pln_out_d_acchdvehwidth_sg_;
  int pln_out_indx_accobjsnsr_en_;
  int pln_out_indx_accobjtracksts_en_;
  int pln_out_indx_accobjmvsts_en_;
  int pln_out_indx_accobjclass_en_;
  bool pln_out_dfin_is_movobjprtctwrn_bl_;
  bool pln_out_dfin_is_stnobjprtctwrn_bl_;
  bool pln_out_dfin_is_codppedwrn_bl_;
  bool pln_out_acc_is_vldmovobjturndscrd_bl_;
  float pln_out_dfin_t_accmovttc_sg_;
  float pln_out_dfin_t_accstnttc_sg_;
  bool pln_out_vldmovobjdscrdexit_bl_;
  bool pln_out_acc_is_vldstnobjturndscrd_bl_;
  bool pln_out_acc_is_vldstnobjdscrdexit_bl_;
  bool pln_out_dfin_is_codpobjnsl_bl_;
  bool pln_out_dfin_is_tgtlgtdisndf_bl_;
  bool pln_out_dfin_is_codplgtftex_bl_;
  bool pln_out_acc_is_acc03cutinsure_bl_;
  bool pln_out_acc_is_acc04cutinsure_bl_;
  float pln_out_k_destrajc0_sg_;
  float pln_out_k_destrajc1_sg_;
  float pln_out_k_destrajc2_sg_;
  float pln_out_k_destrajc3_sg_;
  float pln_out_k_destrajc4_sg_;
  float pln_out_k_destrajc5_sg_;
  float pln_out_d_destrajsend_sg_;
  float pln_out_d_destrajsego_sg_;
  int pln_out_sts_replnlvl_erpl_;
  float pln_out_m_strajerror_sg_;
  float pln_out_v_spdtrajcmd_sg_;
  float pln_out_a_acctrajcmd_sg_;
  ::google::protobuf::int32 pln_out_is_longtraj_replan_level_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ads_5fpln_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PLN_Outputs

// bool PLN_OUT_ACC_is_CLDPLaneErr_bl = 1;
inline void PLN_Outputs::clear_pln_out_acc_is_cldplaneerr_bl() {
  pln_out_acc_is_cldplaneerr_bl_ = false;
}
inline bool PLN_Outputs::pln_out_acc_is_cldplaneerr_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_CLDPLaneErr_bl)
  return pln_out_acc_is_cldplaneerr_bl_;
}
inline void PLN_Outputs::set_pln_out_acc_is_cldplaneerr_bl(bool value) {
  
  pln_out_acc_is_cldplaneerr_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_CLDPLaneErr_bl)
}

// float PLN_OUT_ACC_r_CLDPLaneRadius_sg = 2;
inline void PLN_Outputs::clear_pln_out_acc_r_cldplaneradius_sg() {
  pln_out_acc_r_cldplaneradius_sg_ = 0;
}
inline float PLN_Outputs::pln_out_acc_r_cldplaneradius_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_ACC_r_CLDPLaneRadius_sg)
  return pln_out_acc_r_cldplaneradius_sg_;
}
inline void PLN_Outputs::set_pln_out_acc_r_cldplaneradius_sg(float value) {
  
  pln_out_acc_r_cldplaneradius_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_ACC_r_CLDPLaneRadius_sg)
}

// float PLN_OUT_cv_CLDPDynTrajParA2_sg = 3;
inline void PLN_Outputs::clear_pln_out_cv_cldpdyntrajpara2_sg() {
  pln_out_cv_cldpdyntrajpara2_sg_ = 0;
}
inline float PLN_Outputs::pln_out_cv_cldpdyntrajpara2_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_cv_CLDPDynTrajParA2_sg)
  return pln_out_cv_cldpdyntrajpara2_sg_;
}
inline void PLN_Outputs::set_pln_out_cv_cldpdyntrajpara2_sg(float value) {
  
  pln_out_cv_cldpdyntrajpara2_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_cv_CLDPDynTrajParA2_sg)
}

// float PLN_OUT_cvr_CLDPDynTrajParA3_sg = 4;
inline void PLN_Outputs::clear_pln_out_cvr_cldpdyntrajpara3_sg() {
  pln_out_cvr_cldpdyntrajpara3_sg_ = 0;
}
inline float PLN_Outputs::pln_out_cvr_cldpdyntrajpara3_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_cvr_CLDPDynTrajParA3_sg)
  return pln_out_cvr_cldpdyntrajpara3_sg_;
}
inline void PLN_Outputs::set_pln_out_cvr_cldpdyntrajpara3_sg(float value) {
  
  pln_out_cvr_cldpdyntrajpara3_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_cvr_CLDPDynTrajParA3_sg)
}

// bool PLN_OUT_ACC_is_CLDPEmgrLneChgRAW_bl = 5;
inline void PLN_Outputs::clear_pln_out_acc_is_cldpemgrlnechgraw_bl() {
  pln_out_acc_is_cldpemgrlnechgraw_bl_ = false;
}
inline bool PLN_Outputs::pln_out_acc_is_cldpemgrlnechgraw_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_CLDPEmgrLneChgRAW_bl)
  return pln_out_acc_is_cldpemgrlnechgraw_bl_;
}
inline void PLN_Outputs::set_pln_out_acc_is_cldpemgrlnechgraw_bl(bool value) {
  
  pln_out_acc_is_cldpemgrlnechgraw_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_CLDPEmgrLneChgRAW_bl)
}

// bool PLN_OUT_ACC_is_CLDPEmgrLneChg_bl = 6;
inline void PLN_Outputs::clear_pln_out_acc_is_cldpemgrlnechg_bl() {
  pln_out_acc_is_cldpemgrlnechg_bl_ = false;
}
inline bool PLN_Outputs::pln_out_acc_is_cldpemgrlnechg_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_CLDPEmgrLneChg_bl)
  return pln_out_acc_is_cldpemgrlnechg_bl_;
}
inline void PLN_Outputs::set_pln_out_acc_is_cldpemgrlnechg_bl(bool value) {
  
  pln_out_acc_is_cldpemgrlnechg_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_CLDPEmgrLneChg_bl)
}

// bool PLN_OUT_is_CLDPLftLneCrosBgn_bl = 7;
inline void PLN_Outputs::clear_pln_out_is_cldplftlnecrosbgn_bl() {
  pln_out_is_cldplftlnecrosbgn_bl_ = false;
}
inline bool PLN_Outputs::pln_out_is_cldplftlnecrosbgn_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_is_CLDPLftLneCrosBgn_bl)
  return pln_out_is_cldplftlnecrosbgn_bl_;
}
inline void PLN_Outputs::set_pln_out_is_cldplftlnecrosbgn_bl(bool value) {
  
  pln_out_is_cldplftlnecrosbgn_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_is_CLDPLftLneCrosBgn_bl)
}

// bool PLN_OUT_is_CLDPRgtLneCrosBgn_bl = 8;
inline void PLN_Outputs::clear_pln_out_is_cldprgtlnecrosbgn_bl() {
  pln_out_is_cldprgtlnecrosbgn_bl_ = false;
}
inline bool PLN_Outputs::pln_out_is_cldprgtlnecrosbgn_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_is_CLDPRgtLneCrosBgn_bl)
  return pln_out_is_cldprgtlnecrosbgn_bl_;
}
inline void PLN_Outputs::set_pln_out_is_cldprgtlnecrosbgn_bl(bool value) {
  
  pln_out_is_cldprgtlnecrosbgn_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_is_CLDPRgtLneCrosBgn_bl)
}

// bool PLN_OUT_is_CLDPLftLneCrosEnd_bl = 9;
inline void PLN_Outputs::clear_pln_out_is_cldplftlnecrosend_bl() {
  pln_out_is_cldplftlnecrosend_bl_ = false;
}
inline bool PLN_Outputs::pln_out_is_cldplftlnecrosend_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_is_CLDPLftLneCrosEnd_bl)
  return pln_out_is_cldplftlnecrosend_bl_;
}
inline void PLN_Outputs::set_pln_out_is_cldplftlnecrosend_bl(bool value) {
  
  pln_out_is_cldplftlnecrosend_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_is_CLDPLftLneCrosEnd_bl)
}

// bool PLN_OUT_is_CLDPRgtLneCrosEnd_bl = 10;
inline void PLN_Outputs::clear_pln_out_is_cldprgtlnecrosend_bl() {
  pln_out_is_cldprgtlnecrosend_bl_ = false;
}
inline bool PLN_Outputs::pln_out_is_cldprgtlnecrosend_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_is_CLDPRgtLneCrosEnd_bl)
  return pln_out_is_cldprgtlnecrosend_bl_;
}
inline void PLN_Outputs::set_pln_out_is_cldprgtlnecrosend_bl(bool value) {
  
  pln_out_is_cldprgtlnecrosend_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_is_CLDPRgtLneCrosEnd_bl)
}

// bool PLN_OUT_is_CODPFoloTgtExist_bl = 11;
inline void PLN_Outputs::clear_pln_out_is_codpfolotgtexist_bl() {
  pln_out_is_codpfolotgtexist_bl_ = false;
}
inline bool PLN_Outputs::pln_out_is_codpfolotgtexist_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_is_CODPFoloTgtExist_bl)
  return pln_out_is_codpfolotgtexist_bl_;
}
inline void PLN_Outputs::set_pln_out_is_codpfolotgtexist_bl(bool value) {
  
  pln_out_is_codpfolotgtexist_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_is_CODPFoloTgtExist_bl)
}

// float PLN_OUT_d_CODPFMRdrLatDist_sg = 12;
inline void PLN_Outputs::clear_pln_out_d_codpfmrdrlatdist_sg() {
  pln_out_d_codpfmrdrlatdist_sg_ = 0;
}
inline float PLN_Outputs::pln_out_d_codpfmrdrlatdist_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_d_CODPFMRdrLatDist_sg)
  return pln_out_d_codpfmrdrlatdist_sg_;
}
inline void PLN_Outputs::set_pln_out_d_codpfmrdrlatdist_sg(float value) {
  
  pln_out_d_codpfmrdrlatdist_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_d_CODPFMRdrLatDist_sg)
}

// float PLN_OUT_v_CODPACCLongtRltvSpd_sg = 13;
inline void PLN_Outputs::clear_pln_out_v_codpacclongtrltvspd_sg() {
  pln_out_v_codpacclongtrltvspd_sg_ = 0;
}
inline float PLN_Outputs::pln_out_v_codpacclongtrltvspd_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_v_CODPACCLongtRltvSpd_sg)
  return pln_out_v_codpacclongtrltvspd_sg_;
}
inline void PLN_Outputs::set_pln_out_v_codpacclongtrltvspd_sg(float value) {
  
  pln_out_v_codpacclongtrltvspd_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_v_CODPACCLongtRltvSpd_sg)
}

// float PLN_OUT_v_CODPACCHdVehSpd_sg = 14;
inline void PLN_Outputs::clear_pln_out_v_codpacchdvehspd_sg() {
  pln_out_v_codpacchdvehspd_sg_ = 0;
}
inline float PLN_Outputs::pln_out_v_codpacchdvehspd_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_v_CODPACCHdVehSpd_sg)
  return pln_out_v_codpacchdvehspd_sg_;
}
inline void PLN_Outputs::set_pln_out_v_codpacchdvehspd_sg(float value) {
  
  pln_out_v_codpacchdvehspd_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_v_CODPACCHdVehSpd_sg)
}

// float PLN_OUT_d_CODPACCFMRdrLongtDist_sg = 15;
inline void PLN_Outputs::clear_pln_out_d_codpaccfmrdrlongtdist_sg() {
  pln_out_d_codpaccfmrdrlongtdist_sg_ = 0;
}
inline float PLN_Outputs::pln_out_d_codpaccfmrdrlongtdist_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_d_CODPACCFMRdrLongtDist_sg)
  return pln_out_d_codpaccfmrdrlongtdist_sg_;
}
inline void PLN_Outputs::set_pln_out_d_codpaccfmrdrlongtdist_sg(float value) {
  
  pln_out_d_codpaccfmrdrlongtdist_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_d_CODPACCFMRdrLongtDist_sg)
}

// sint32 PLN_OUT_indx_CODPACCTgtID_u8 = 16;
inline void PLN_Outputs::clear_pln_out_indx_codpacctgtid_u8() {
  pln_out_indx_codpacctgtid_u8_ = 0;
}
inline ::google::protobuf::int32 PLN_Outputs::pln_out_indx_codpacctgtid_u8() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_indx_CODPACCTgtID_u8)
  return pln_out_indx_codpacctgtid_u8_;
}
inline void PLN_Outputs::set_pln_out_indx_codpacctgtid_u8(::google::protobuf::int32 value) {
  
  pln_out_indx_codpacctgtid_u8_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_indx_CODPACCTgtID_u8)
}

// float PLN_OUT_v_ACCHdVehLatSpd_sg = 17;
inline void PLN_Outputs::clear_pln_out_v_acchdvehlatspd_sg() {
  pln_out_v_acchdvehlatspd_sg_ = 0;
}
inline float PLN_Outputs::pln_out_v_acchdvehlatspd_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_v_ACCHdVehLatSpd_sg)
  return pln_out_v_acchdvehlatspd_sg_;
}
inline void PLN_Outputs::set_pln_out_v_acchdvehlatspd_sg(float value) {
  
  pln_out_v_acchdvehlatspd_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_v_ACCHdVehLatSpd_sg)
}

// float PLN_OUT_a_ACCHdVehLgtAcc_sg = 18;
inline void PLN_Outputs::clear_pln_out_a_acchdvehlgtacc_sg() {
  pln_out_a_acchdvehlgtacc_sg_ = 0;
}
inline float PLN_Outputs::pln_out_a_acchdvehlgtacc_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_a_ACCHdVehLgtAcc_sg)
  return pln_out_a_acchdvehlgtacc_sg_;
}
inline void PLN_Outputs::set_pln_out_a_acchdvehlgtacc_sg(float value) {
  
  pln_out_a_acchdvehlgtacc_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_a_ACCHdVehLgtAcc_sg)
}

// float PLN_OUT_a_ACCHdVehLatAcc_sg = 19;
inline void PLN_Outputs::clear_pln_out_a_acchdvehlatacc_sg() {
  pln_out_a_acchdvehlatacc_sg_ = 0;
}
inline float PLN_Outputs::pln_out_a_acchdvehlatacc_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_a_ACCHdVehLatAcc_sg)
  return pln_out_a_acchdvehlatacc_sg_;
}
inline void PLN_Outputs::set_pln_out_a_acchdvehlatacc_sg(float value) {
  
  pln_out_a_acchdvehlatacc_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_a_ACCHdVehLatAcc_sg)
}

// float PLN_OUT_d_ACCHdVehWidth_sg = 20;
inline void PLN_Outputs::clear_pln_out_d_acchdvehwidth_sg() {
  pln_out_d_acchdvehwidth_sg_ = 0;
}
inline float PLN_Outputs::pln_out_d_acchdvehwidth_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_d_ACCHdVehWidth_sg)
  return pln_out_d_acchdvehwidth_sg_;
}
inline void PLN_Outputs::set_pln_out_d_acchdvehwidth_sg(float value) {
  
  pln_out_d_acchdvehwidth_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_d_ACCHdVehWidth_sg)
}

// .ads_common.eCSNR_ACCObjSnsr PLN_OUT_indx_ACCObjSnsr_en = 21;
inline void PLN_Outputs::clear_pln_out_indx_accobjsnsr_en() {
  pln_out_indx_accobjsnsr_en_ = 0;
}
inline ::ads_common::eCSNR_ACCObjSnsr PLN_Outputs::pln_out_indx_accobjsnsr_en() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_indx_ACCObjSnsr_en)
  return static_cast< ::ads_common::eCSNR_ACCObjSnsr >(pln_out_indx_accobjsnsr_en_);
}
inline void PLN_Outputs::set_pln_out_indx_accobjsnsr_en(::ads_common::eCSNR_ACCObjSnsr value) {
  
  pln_out_indx_accobjsnsr_en_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_indx_ACCObjSnsr_en)
}

// .ads_common.eCTRK_ACCObjTrackSts PLN_OUT_indx_ACCObjTrackSts_en = 22;
inline void PLN_Outputs::clear_pln_out_indx_accobjtracksts_en() {
  pln_out_indx_accobjtracksts_en_ = 0;
}
inline ::ads_common::eCTRK_ACCObjTrackSts PLN_Outputs::pln_out_indx_accobjtracksts_en() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_indx_ACCObjTrackSts_en)
  return static_cast< ::ads_common::eCTRK_ACCObjTrackSts >(pln_out_indx_accobjtracksts_en_);
}
inline void PLN_Outputs::set_pln_out_indx_accobjtracksts_en(::ads_common::eCTRK_ACCObjTrackSts value) {
  
  pln_out_indx_accobjtracksts_en_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_indx_ACCObjTrackSts_en)
}

// .ads_common.eCMV_ACCObjMvSts PLN_OUT_indx_ACCObjMvSts_en = 23;
inline void PLN_Outputs::clear_pln_out_indx_accobjmvsts_en() {
  pln_out_indx_accobjmvsts_en_ = 0;
}
inline ::ads_common::eCMV_ACCObjMvSts PLN_Outputs::pln_out_indx_accobjmvsts_en() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_indx_ACCObjMvSts_en)
  return static_cast< ::ads_common::eCMV_ACCObjMvSts >(pln_out_indx_accobjmvsts_en_);
}
inline void PLN_Outputs::set_pln_out_indx_accobjmvsts_en(::ads_common::eCMV_ACCObjMvSts value) {
  
  pln_out_indx_accobjmvsts_en_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_indx_ACCObjMvSts_en)
}

// .ads_common.eCLS_ACCObjClass PLN_OUT_indx_ACCObjClass_en = 24;
inline void PLN_Outputs::clear_pln_out_indx_accobjclass_en() {
  pln_out_indx_accobjclass_en_ = 0;
}
inline ::ads_common::eCLS_ACCObjClass PLN_Outputs::pln_out_indx_accobjclass_en() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_indx_ACCObjClass_en)
  return static_cast< ::ads_common::eCLS_ACCObjClass >(pln_out_indx_accobjclass_en_);
}
inline void PLN_Outputs::set_pln_out_indx_accobjclass_en(::ads_common::eCLS_ACCObjClass value) {
  
  pln_out_indx_accobjclass_en_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_indx_ACCObjClass_en)
}

// .ads_common.B_ACCObjVldLv2 PLN_OUT_CODP_bus_ACCObjVldLv2 = 25;
inline bool PLN_Outputs::has_pln_out_codp_bus_accobjvldlv2() const {
  return this != internal_default_instance() && pln_out_codp_bus_accobjvldlv2_ != NULL;
}
inline const ::ads_common::B_ACCObjVldLv2& PLN_Outputs::_internal_pln_out_codp_bus_accobjvldlv2() const {
  return *pln_out_codp_bus_accobjvldlv2_;
}
inline const ::ads_common::B_ACCObjVldLv2& PLN_Outputs::pln_out_codp_bus_accobjvldlv2() const {
  const ::ads_common::B_ACCObjVldLv2* p = pln_out_codp_bus_accobjvldlv2_;
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_CODP_bus_ACCObjVldLv2)
  return p != NULL ? *p : *reinterpret_cast<const ::ads_common::B_ACCObjVldLv2*>(
      &::ads_common::_B_ACCObjVldLv2_default_instance_);
}
inline ::ads_common::B_ACCObjVldLv2* PLN_Outputs::release_pln_out_codp_bus_accobjvldlv2() {
  // @@protoc_insertion_point(field_release:ads_pln.PLN_Outputs.PLN_OUT_CODP_bus_ACCObjVldLv2)
  
  ::ads_common::B_ACCObjVldLv2* temp = pln_out_codp_bus_accobjvldlv2_;
  pln_out_codp_bus_accobjvldlv2_ = NULL;
  return temp;
}
inline ::ads_common::B_ACCObjVldLv2* PLN_Outputs::mutable_pln_out_codp_bus_accobjvldlv2() {
  
  if (pln_out_codp_bus_accobjvldlv2_ == NULL) {
    auto* p = CreateMaybeMessage<::ads_common::B_ACCObjVldLv2>(GetArenaNoVirtual());
    pln_out_codp_bus_accobjvldlv2_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ads_pln.PLN_Outputs.PLN_OUT_CODP_bus_ACCObjVldLv2)
  return pln_out_codp_bus_accobjvldlv2_;
}
inline void PLN_Outputs::set_allocated_pln_out_codp_bus_accobjvldlv2(::ads_common::B_ACCObjVldLv2* pln_out_codp_bus_accobjvldlv2) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pln_out_codp_bus_accobjvldlv2_);
  }
  if (pln_out_codp_bus_accobjvldlv2) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pln_out_codp_bus_accobjvldlv2 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pln_out_codp_bus_accobjvldlv2, submessage_arena);
    }
    
  } else {
    
  }
  pln_out_codp_bus_accobjvldlv2_ = pln_out_codp_bus_accobjvldlv2;
  // @@protoc_insertion_point(field_set_allocated:ads_pln.PLN_Outputs.PLN_OUT_CODP_bus_ACCObjVldLv2)
}

// .ads_common.B_ACCObj03_st PLN_OUT_DA_IN_bus_ACCObj03 = 26;
inline bool PLN_Outputs::has_pln_out_da_in_bus_accobj03() const {
  return this != internal_default_instance() && pln_out_da_in_bus_accobj03_ != NULL;
}
inline const ::ads_common::B_ACCObj03_st& PLN_Outputs::_internal_pln_out_da_in_bus_accobj03() const {
  return *pln_out_da_in_bus_accobj03_;
}
inline const ::ads_common::B_ACCObj03_st& PLN_Outputs::pln_out_da_in_bus_accobj03() const {
  const ::ads_common::B_ACCObj03_st* p = pln_out_da_in_bus_accobj03_;
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCObj03)
  return p != NULL ? *p : *reinterpret_cast<const ::ads_common::B_ACCObj03_st*>(
      &::ads_common::_B_ACCObj03_st_default_instance_);
}
inline ::ads_common::B_ACCObj03_st* PLN_Outputs::release_pln_out_da_in_bus_accobj03() {
  // @@protoc_insertion_point(field_release:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCObj03)
  
  ::ads_common::B_ACCObj03_st* temp = pln_out_da_in_bus_accobj03_;
  pln_out_da_in_bus_accobj03_ = NULL;
  return temp;
}
inline ::ads_common::B_ACCObj03_st* PLN_Outputs::mutable_pln_out_da_in_bus_accobj03() {
  
  if (pln_out_da_in_bus_accobj03_ == NULL) {
    auto* p = CreateMaybeMessage<::ads_common::B_ACCObj03_st>(GetArenaNoVirtual());
    pln_out_da_in_bus_accobj03_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCObj03)
  return pln_out_da_in_bus_accobj03_;
}
inline void PLN_Outputs::set_allocated_pln_out_da_in_bus_accobj03(::ads_common::B_ACCObj03_st* pln_out_da_in_bus_accobj03) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pln_out_da_in_bus_accobj03_);
  }
  if (pln_out_da_in_bus_accobj03) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pln_out_da_in_bus_accobj03 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pln_out_da_in_bus_accobj03, submessage_arena);
    }
    
  } else {
    
  }
  pln_out_da_in_bus_accobj03_ = pln_out_da_in_bus_accobj03;
  // @@protoc_insertion_point(field_set_allocated:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCObj03)
}

// .ads_common.B_ACCObj04_st PLN_OUT_DA_IN_bus_ACCObj04 = 27;
inline bool PLN_Outputs::has_pln_out_da_in_bus_accobj04() const {
  return this != internal_default_instance() && pln_out_da_in_bus_accobj04_ != NULL;
}
inline const ::ads_common::B_ACCObj04_st& PLN_Outputs::_internal_pln_out_da_in_bus_accobj04() const {
  return *pln_out_da_in_bus_accobj04_;
}
inline const ::ads_common::B_ACCObj04_st& PLN_Outputs::pln_out_da_in_bus_accobj04() const {
  const ::ads_common::B_ACCObj04_st* p = pln_out_da_in_bus_accobj04_;
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCObj04)
  return p != NULL ? *p : *reinterpret_cast<const ::ads_common::B_ACCObj04_st*>(
      &::ads_common::_B_ACCObj04_st_default_instance_);
}
inline ::ads_common::B_ACCObj04_st* PLN_Outputs::release_pln_out_da_in_bus_accobj04() {
  // @@protoc_insertion_point(field_release:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCObj04)
  
  ::ads_common::B_ACCObj04_st* temp = pln_out_da_in_bus_accobj04_;
  pln_out_da_in_bus_accobj04_ = NULL;
  return temp;
}
inline ::ads_common::B_ACCObj04_st* PLN_Outputs::mutable_pln_out_da_in_bus_accobj04() {
  
  if (pln_out_da_in_bus_accobj04_ == NULL) {
    auto* p = CreateMaybeMessage<::ads_common::B_ACCObj04_st>(GetArenaNoVirtual());
    pln_out_da_in_bus_accobj04_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCObj04)
  return pln_out_da_in_bus_accobj04_;
}
inline void PLN_Outputs::set_allocated_pln_out_da_in_bus_accobj04(::ads_common::B_ACCObj04_st* pln_out_da_in_bus_accobj04) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pln_out_da_in_bus_accobj04_);
  }
  if (pln_out_da_in_bus_accobj04) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pln_out_da_in_bus_accobj04 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pln_out_da_in_bus_accobj04, submessage_arena);
    }
    
  } else {
    
  }
  pln_out_da_in_bus_accobj04_ = pln_out_da_in_bus_accobj04;
  // @@protoc_insertion_point(field_set_allocated:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCObj04)
}

// .ads_common.B_ACCStnObj03_st PLN_OUT_DA_IN_bus_ACCStnObj03 = 28;
inline bool PLN_Outputs::has_pln_out_da_in_bus_accstnobj03() const {
  return this != internal_default_instance() && pln_out_da_in_bus_accstnobj03_ != NULL;
}
inline const ::ads_common::B_ACCStnObj03_st& PLN_Outputs::_internal_pln_out_da_in_bus_accstnobj03() const {
  return *pln_out_da_in_bus_accstnobj03_;
}
inline const ::ads_common::B_ACCStnObj03_st& PLN_Outputs::pln_out_da_in_bus_accstnobj03() const {
  const ::ads_common::B_ACCStnObj03_st* p = pln_out_da_in_bus_accstnobj03_;
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCStnObj03)
  return p != NULL ? *p : *reinterpret_cast<const ::ads_common::B_ACCStnObj03_st*>(
      &::ads_common::_B_ACCStnObj03_st_default_instance_);
}
inline ::ads_common::B_ACCStnObj03_st* PLN_Outputs::release_pln_out_da_in_bus_accstnobj03() {
  // @@protoc_insertion_point(field_release:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCStnObj03)
  
  ::ads_common::B_ACCStnObj03_st* temp = pln_out_da_in_bus_accstnobj03_;
  pln_out_da_in_bus_accstnobj03_ = NULL;
  return temp;
}
inline ::ads_common::B_ACCStnObj03_st* PLN_Outputs::mutable_pln_out_da_in_bus_accstnobj03() {
  
  if (pln_out_da_in_bus_accstnobj03_ == NULL) {
    auto* p = CreateMaybeMessage<::ads_common::B_ACCStnObj03_st>(GetArenaNoVirtual());
    pln_out_da_in_bus_accstnobj03_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCStnObj03)
  return pln_out_da_in_bus_accstnobj03_;
}
inline void PLN_Outputs::set_allocated_pln_out_da_in_bus_accstnobj03(::ads_common::B_ACCStnObj03_st* pln_out_da_in_bus_accstnobj03) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pln_out_da_in_bus_accstnobj03_);
  }
  if (pln_out_da_in_bus_accstnobj03) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pln_out_da_in_bus_accstnobj03 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pln_out_da_in_bus_accstnobj03, submessage_arena);
    }
    
  } else {
    
  }
  pln_out_da_in_bus_accstnobj03_ = pln_out_da_in_bus_accstnobj03;
  // @@protoc_insertion_point(field_set_allocated:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCStnObj03)
}

// .ads_common.B_ACCStnObj04_st PLN_OUT_DA_IN_bus_ACCStnObj04 = 29;
inline bool PLN_Outputs::has_pln_out_da_in_bus_accstnobj04() const {
  return this != internal_default_instance() && pln_out_da_in_bus_accstnobj04_ != NULL;
}
inline const ::ads_common::B_ACCStnObj04_st& PLN_Outputs::_internal_pln_out_da_in_bus_accstnobj04() const {
  return *pln_out_da_in_bus_accstnobj04_;
}
inline const ::ads_common::B_ACCStnObj04_st& PLN_Outputs::pln_out_da_in_bus_accstnobj04() const {
  const ::ads_common::B_ACCStnObj04_st* p = pln_out_da_in_bus_accstnobj04_;
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCStnObj04)
  return p != NULL ? *p : *reinterpret_cast<const ::ads_common::B_ACCStnObj04_st*>(
      &::ads_common::_B_ACCStnObj04_st_default_instance_);
}
inline ::ads_common::B_ACCStnObj04_st* PLN_Outputs::release_pln_out_da_in_bus_accstnobj04() {
  // @@protoc_insertion_point(field_release:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCStnObj04)
  
  ::ads_common::B_ACCStnObj04_st* temp = pln_out_da_in_bus_accstnobj04_;
  pln_out_da_in_bus_accstnobj04_ = NULL;
  return temp;
}
inline ::ads_common::B_ACCStnObj04_st* PLN_Outputs::mutable_pln_out_da_in_bus_accstnobj04() {
  
  if (pln_out_da_in_bus_accstnobj04_ == NULL) {
    auto* p = CreateMaybeMessage<::ads_common::B_ACCStnObj04_st>(GetArenaNoVirtual());
    pln_out_da_in_bus_accstnobj04_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCStnObj04)
  return pln_out_da_in_bus_accstnobj04_;
}
inline void PLN_Outputs::set_allocated_pln_out_da_in_bus_accstnobj04(::ads_common::B_ACCStnObj04_st* pln_out_da_in_bus_accstnobj04) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pln_out_da_in_bus_accstnobj04_);
  }
  if (pln_out_da_in_bus_accstnobj04) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pln_out_da_in_bus_accstnobj04 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pln_out_da_in_bus_accstnobj04, submessage_arena);
    }
    
  } else {
    
  }
  pln_out_da_in_bus_accstnobj04_ = pln_out_da_in_bus_accstnobj04;
  // @@protoc_insertion_point(field_set_allocated:ads_pln.PLN_Outputs.PLN_OUT_DA_IN_bus_ACCStnObj04)
}

// .ads_common.B_ACCObjVldRaw PLN_OUT_CODP_bus_ACCObjVldRaw = 30;
inline bool PLN_Outputs::has_pln_out_codp_bus_accobjvldraw() const {
  return this != internal_default_instance() && pln_out_codp_bus_accobjvldraw_ != NULL;
}
inline const ::ads_common::B_ACCObjVldRaw& PLN_Outputs::_internal_pln_out_codp_bus_accobjvldraw() const {
  return *pln_out_codp_bus_accobjvldraw_;
}
inline const ::ads_common::B_ACCObjVldRaw& PLN_Outputs::pln_out_codp_bus_accobjvldraw() const {
  const ::ads_common::B_ACCObjVldRaw* p = pln_out_codp_bus_accobjvldraw_;
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_CODP_bus_ACCObjVldRaw)
  return p != NULL ? *p : *reinterpret_cast<const ::ads_common::B_ACCObjVldRaw*>(
      &::ads_common::_B_ACCObjVldRaw_default_instance_);
}
inline ::ads_common::B_ACCObjVldRaw* PLN_Outputs::release_pln_out_codp_bus_accobjvldraw() {
  // @@protoc_insertion_point(field_release:ads_pln.PLN_Outputs.PLN_OUT_CODP_bus_ACCObjVldRaw)
  
  ::ads_common::B_ACCObjVldRaw* temp = pln_out_codp_bus_accobjvldraw_;
  pln_out_codp_bus_accobjvldraw_ = NULL;
  return temp;
}
inline ::ads_common::B_ACCObjVldRaw* PLN_Outputs::mutable_pln_out_codp_bus_accobjvldraw() {
  
  if (pln_out_codp_bus_accobjvldraw_ == NULL) {
    auto* p = CreateMaybeMessage<::ads_common::B_ACCObjVldRaw>(GetArenaNoVirtual());
    pln_out_codp_bus_accobjvldraw_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ads_pln.PLN_Outputs.PLN_OUT_CODP_bus_ACCObjVldRaw)
  return pln_out_codp_bus_accobjvldraw_;
}
inline void PLN_Outputs::set_allocated_pln_out_codp_bus_accobjvldraw(::ads_common::B_ACCObjVldRaw* pln_out_codp_bus_accobjvldraw) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pln_out_codp_bus_accobjvldraw_);
  }
  if (pln_out_codp_bus_accobjvldraw) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pln_out_codp_bus_accobjvldraw = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pln_out_codp_bus_accobjvldraw, submessage_arena);
    }
    
  } else {
    
  }
  pln_out_codp_bus_accobjvldraw_ = pln_out_codp_bus_accobjvldraw;
  // @@protoc_insertion_point(field_set_allocated:ads_pln.PLN_Outputs.PLN_OUT_CODP_bus_ACCObjVldRaw)
}

// bool PLN_OUT_DFIn_is_MovObjPrtctWrn_bl = 31;
inline void PLN_Outputs::clear_pln_out_dfin_is_movobjprtctwrn_bl() {
  pln_out_dfin_is_movobjprtctwrn_bl_ = false;
}
inline bool PLN_Outputs::pln_out_dfin_is_movobjprtctwrn_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_MovObjPrtctWrn_bl)
  return pln_out_dfin_is_movobjprtctwrn_bl_;
}
inline void PLN_Outputs::set_pln_out_dfin_is_movobjprtctwrn_bl(bool value) {
  
  pln_out_dfin_is_movobjprtctwrn_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_MovObjPrtctWrn_bl)
}

// bool PLN_OUT_DFIn_is_StnObjPrtctWrn_bl = 32;
inline void PLN_Outputs::clear_pln_out_dfin_is_stnobjprtctwrn_bl() {
  pln_out_dfin_is_stnobjprtctwrn_bl_ = false;
}
inline bool PLN_Outputs::pln_out_dfin_is_stnobjprtctwrn_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_StnObjPrtctWrn_bl)
  return pln_out_dfin_is_stnobjprtctwrn_bl_;
}
inline void PLN_Outputs::set_pln_out_dfin_is_stnobjprtctwrn_bl(bool value) {
  
  pln_out_dfin_is_stnobjprtctwrn_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_StnObjPrtctWrn_bl)
}

// bool PLN_OUT_DFIn_is_CODPPedWrn_bl = 33;
inline void PLN_Outputs::clear_pln_out_dfin_is_codppedwrn_bl() {
  pln_out_dfin_is_codppedwrn_bl_ = false;
}
inline bool PLN_Outputs::pln_out_dfin_is_codppedwrn_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_CODPPedWrn_bl)
  return pln_out_dfin_is_codppedwrn_bl_;
}
inline void PLN_Outputs::set_pln_out_dfin_is_codppedwrn_bl(bool value) {
  
  pln_out_dfin_is_codppedwrn_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_CODPPedWrn_bl)
}

// float PLN_OUT_DFIn_t_ACCMovTTC_sg = 34;
inline void PLN_Outputs::clear_pln_out_dfin_t_accmovttc_sg() {
  pln_out_dfin_t_accmovttc_sg_ = 0;
}
inline float PLN_Outputs::pln_out_dfin_t_accmovttc_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DFIn_t_ACCMovTTC_sg)
  return pln_out_dfin_t_accmovttc_sg_;
}
inline void PLN_Outputs::set_pln_out_dfin_t_accmovttc_sg(float value) {
  
  pln_out_dfin_t_accmovttc_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_DFIn_t_ACCMovTTC_sg)
}

// float PLN_OUT_DFIn_t_ACCStnTTC_sg = 35;
inline void PLN_Outputs::clear_pln_out_dfin_t_accstnttc_sg() {
  pln_out_dfin_t_accstnttc_sg_ = 0;
}
inline float PLN_Outputs::pln_out_dfin_t_accstnttc_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DFIn_t_ACCStnTTC_sg)
  return pln_out_dfin_t_accstnttc_sg_;
}
inline void PLN_Outputs::set_pln_out_dfin_t_accstnttc_sg(float value) {
  
  pln_out_dfin_t_accstnttc_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_DFIn_t_ACCStnTTC_sg)
}

// bool PLN_OUT_ACC_is_VldMovObjTurnDscrd_bl = 36;
inline void PLN_Outputs::clear_pln_out_acc_is_vldmovobjturndscrd_bl() {
  pln_out_acc_is_vldmovobjturndscrd_bl_ = false;
}
inline bool PLN_Outputs::pln_out_acc_is_vldmovobjturndscrd_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_VldMovObjTurnDscrd_bl)
  return pln_out_acc_is_vldmovobjturndscrd_bl_;
}
inline void PLN_Outputs::set_pln_out_acc_is_vldmovobjturndscrd_bl(bool value) {
  
  pln_out_acc_is_vldmovobjturndscrd_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_VldMovObjTurnDscrd_bl)
}

// bool PLN_OUT_VldMovObjDscrdExit_bl = 37;
inline void PLN_Outputs::clear_pln_out_vldmovobjdscrdexit_bl() {
  pln_out_vldmovobjdscrdexit_bl_ = false;
}
inline bool PLN_Outputs::pln_out_vldmovobjdscrdexit_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_VldMovObjDscrdExit_bl)
  return pln_out_vldmovobjdscrdexit_bl_;
}
inline void PLN_Outputs::set_pln_out_vldmovobjdscrdexit_bl(bool value) {
  
  pln_out_vldmovobjdscrdexit_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_VldMovObjDscrdExit_bl)
}

// bool PLN_OUT_ACC_is_VldStnObjTurnDscrd_bl = 38;
inline void PLN_Outputs::clear_pln_out_acc_is_vldstnobjturndscrd_bl() {
  pln_out_acc_is_vldstnobjturndscrd_bl_ = false;
}
inline bool PLN_Outputs::pln_out_acc_is_vldstnobjturndscrd_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_VldStnObjTurnDscrd_bl)
  return pln_out_acc_is_vldstnobjturndscrd_bl_;
}
inline void PLN_Outputs::set_pln_out_acc_is_vldstnobjturndscrd_bl(bool value) {
  
  pln_out_acc_is_vldstnobjturndscrd_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_VldStnObjTurnDscrd_bl)
}

// bool PLN_OUT_ACC_is_VldStnObjDscrdExit_bl = 39;
inline void PLN_Outputs::clear_pln_out_acc_is_vldstnobjdscrdexit_bl() {
  pln_out_acc_is_vldstnobjdscrdexit_bl_ = false;
}
inline bool PLN_Outputs::pln_out_acc_is_vldstnobjdscrdexit_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_VldStnObjDscrdExit_bl)
  return pln_out_acc_is_vldstnobjdscrdexit_bl_;
}
inline void PLN_Outputs::set_pln_out_acc_is_vldstnobjdscrdexit_bl(bool value) {
  
  pln_out_acc_is_vldstnobjdscrdexit_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_VldStnObjDscrdExit_bl)
}

// bool PLN_OUT_DFIn_is_CODPObjNSL_bl = 40;
inline void PLN_Outputs::clear_pln_out_dfin_is_codpobjnsl_bl() {
  pln_out_dfin_is_codpobjnsl_bl_ = false;
}
inline bool PLN_Outputs::pln_out_dfin_is_codpobjnsl_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_CODPObjNSL_bl)
  return pln_out_dfin_is_codpobjnsl_bl_;
}
inline void PLN_Outputs::set_pln_out_dfin_is_codpobjnsl_bl(bool value) {
  
  pln_out_dfin_is_codpobjnsl_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_CODPObjNSL_bl)
}

// bool PLN_OUT_DFIn_is_TgtLgtDisNdF_bl = 41;
inline void PLN_Outputs::clear_pln_out_dfin_is_tgtlgtdisndf_bl() {
  pln_out_dfin_is_tgtlgtdisndf_bl_ = false;
}
inline bool PLN_Outputs::pln_out_dfin_is_tgtlgtdisndf_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_TgtLgtDisNdF_bl)
  return pln_out_dfin_is_tgtlgtdisndf_bl_;
}
inline void PLN_Outputs::set_pln_out_dfin_is_tgtlgtdisndf_bl(bool value) {
  
  pln_out_dfin_is_tgtlgtdisndf_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_TgtLgtDisNdF_bl)
}

// bool PLN_OUT_DFIn_is_CODPLgtFtEX_bl = 42;
inline void PLN_Outputs::clear_pln_out_dfin_is_codplgtftex_bl() {
  pln_out_dfin_is_codplgtftex_bl_ = false;
}
inline bool PLN_Outputs::pln_out_dfin_is_codplgtftex_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_CODPLgtFtEX_bl)
  return pln_out_dfin_is_codplgtftex_bl_;
}
inline void PLN_Outputs::set_pln_out_dfin_is_codplgtftex_bl(bool value) {
  
  pln_out_dfin_is_codplgtftex_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_DFIn_is_CODPLgtFtEX_bl)
}

// bool PLN_OUT_ACC_is_ACC03CutinSure_bl = 43;
inline void PLN_Outputs::clear_pln_out_acc_is_acc03cutinsure_bl() {
  pln_out_acc_is_acc03cutinsure_bl_ = false;
}
inline bool PLN_Outputs::pln_out_acc_is_acc03cutinsure_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_ACC03CutinSure_bl)
  return pln_out_acc_is_acc03cutinsure_bl_;
}
inline void PLN_Outputs::set_pln_out_acc_is_acc03cutinsure_bl(bool value) {
  
  pln_out_acc_is_acc03cutinsure_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_ACC03CutinSure_bl)
}

// bool PLN_OUT_ACC_is_ACC04CutinSure_bl = 44;
inline void PLN_Outputs::clear_pln_out_acc_is_acc04cutinsure_bl() {
  pln_out_acc_is_acc04cutinsure_bl_ = false;
}
inline bool PLN_Outputs::pln_out_acc_is_acc04cutinsure_bl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_ACC04CutinSure_bl)
  return pln_out_acc_is_acc04cutinsure_bl_;
}
inline void PLN_Outputs::set_pln_out_acc_is_acc04cutinsure_bl(bool value) {
  
  pln_out_acc_is_acc04cutinsure_bl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_ACC_is_ACC04CutinSure_bl)
}

// float PLN_OUT_K_DesTrajC0_sg = 45;
inline void PLN_Outputs::clear_pln_out_k_destrajc0_sg() {
  pln_out_k_destrajc0_sg_ = 0;
}
inline float PLN_Outputs::pln_out_k_destrajc0_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC0_sg)
  return pln_out_k_destrajc0_sg_;
}
inline void PLN_Outputs::set_pln_out_k_destrajc0_sg(float value) {
  
  pln_out_k_destrajc0_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC0_sg)
}

// float PLN_OUT_K_DesTrajC1_sg = 46;
inline void PLN_Outputs::clear_pln_out_k_destrajc1_sg() {
  pln_out_k_destrajc1_sg_ = 0;
}
inline float PLN_Outputs::pln_out_k_destrajc1_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC1_sg)
  return pln_out_k_destrajc1_sg_;
}
inline void PLN_Outputs::set_pln_out_k_destrajc1_sg(float value) {
  
  pln_out_k_destrajc1_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC1_sg)
}

// float PLN_OUT_K_DesTrajC2_sg = 47;
inline void PLN_Outputs::clear_pln_out_k_destrajc2_sg() {
  pln_out_k_destrajc2_sg_ = 0;
}
inline float PLN_Outputs::pln_out_k_destrajc2_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC2_sg)
  return pln_out_k_destrajc2_sg_;
}
inline void PLN_Outputs::set_pln_out_k_destrajc2_sg(float value) {
  
  pln_out_k_destrajc2_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC2_sg)
}

// float PLN_OUT_K_DesTrajC3_sg = 48;
inline void PLN_Outputs::clear_pln_out_k_destrajc3_sg() {
  pln_out_k_destrajc3_sg_ = 0;
}
inline float PLN_Outputs::pln_out_k_destrajc3_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC3_sg)
  return pln_out_k_destrajc3_sg_;
}
inline void PLN_Outputs::set_pln_out_k_destrajc3_sg(float value) {
  
  pln_out_k_destrajc3_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC3_sg)
}

// float PLN_OUT_K_DesTrajC4_sg = 49;
inline void PLN_Outputs::clear_pln_out_k_destrajc4_sg() {
  pln_out_k_destrajc4_sg_ = 0;
}
inline float PLN_Outputs::pln_out_k_destrajc4_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC4_sg)
  return pln_out_k_destrajc4_sg_;
}
inline void PLN_Outputs::set_pln_out_k_destrajc4_sg(float value) {
  
  pln_out_k_destrajc4_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC4_sg)
}

// float PLN_OUT_K_DesTrajC5_sg = 50;
inline void PLN_Outputs::clear_pln_out_k_destrajc5_sg() {
  pln_out_k_destrajc5_sg_ = 0;
}
inline float PLN_Outputs::pln_out_k_destrajc5_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC5_sg)
  return pln_out_k_destrajc5_sg_;
}
inline void PLN_Outputs::set_pln_out_k_destrajc5_sg(float value) {
  
  pln_out_k_destrajc5_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_K_DesTrajC5_sg)
}

// float PLN_OUT_d_DesTrajSend_sg = 51;
inline void PLN_Outputs::clear_pln_out_d_destrajsend_sg() {
  pln_out_d_destrajsend_sg_ = 0;
}
inline float PLN_Outputs::pln_out_d_destrajsend_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_d_DesTrajSend_sg)
  return pln_out_d_destrajsend_sg_;
}
inline void PLN_Outputs::set_pln_out_d_destrajsend_sg(float value) {
  
  pln_out_d_destrajsend_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_d_DesTrajSend_sg)
}

// float PLN_OUT_d_DesTrajSego_sg = 52;
inline void PLN_Outputs::clear_pln_out_d_destrajsego_sg() {
  pln_out_d_destrajsego_sg_ = 0;
}
inline float PLN_Outputs::pln_out_d_destrajsego_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_d_DesTrajSego_sg)
  return pln_out_d_destrajsego_sg_;
}
inline void PLN_Outputs::set_pln_out_d_destrajsego_sg(float value) {
  
  pln_out_d_destrajsego_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_d_DesTrajSego_sg)
}

// .ads_common.eRPL_RePlanLevel PLN_OUT_sts_ReplnLvl_eRPL = 53;
inline void PLN_Outputs::clear_pln_out_sts_replnlvl_erpl() {
  pln_out_sts_replnlvl_erpl_ = 0;
}
inline ::ads_common::eRPL_RePlanLevel PLN_Outputs::pln_out_sts_replnlvl_erpl() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_sts_ReplnLvl_eRPL)
  return static_cast< ::ads_common::eRPL_RePlanLevel >(pln_out_sts_replnlvl_erpl_);
}
inline void PLN_Outputs::set_pln_out_sts_replnlvl_erpl(::ads_common::eRPL_RePlanLevel value) {
  
  pln_out_sts_replnlvl_erpl_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_sts_ReplnLvl_eRPL)
}

// float PLN_OUT_m_STrajError_sg = 54;
inline void PLN_Outputs::clear_pln_out_m_strajerror_sg() {
  pln_out_m_strajerror_sg_ = 0;
}
inline float PLN_Outputs::pln_out_m_strajerror_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_m_STrajError_sg)
  return pln_out_m_strajerror_sg_;
}
inline void PLN_Outputs::set_pln_out_m_strajerror_sg(float value) {
  
  pln_out_m_strajerror_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_m_STrajError_sg)
}

// float PLN_OUT_v_SpdTrajCmd_sg = 55;
inline void PLN_Outputs::clear_pln_out_v_spdtrajcmd_sg() {
  pln_out_v_spdtrajcmd_sg_ = 0;
}
inline float PLN_Outputs::pln_out_v_spdtrajcmd_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_v_SpdTrajCmd_sg)
  return pln_out_v_spdtrajcmd_sg_;
}
inline void PLN_Outputs::set_pln_out_v_spdtrajcmd_sg(float value) {
  
  pln_out_v_spdtrajcmd_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_v_SpdTrajCmd_sg)
}

// float PLN_OUT_a_AccTrajCmd_sg = 56;
inline void PLN_Outputs::clear_pln_out_a_acctrajcmd_sg() {
  pln_out_a_acctrajcmd_sg_ = 0;
}
inline float PLN_Outputs::pln_out_a_acctrajcmd_sg() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_a_AccTrajCmd_sg)
  return pln_out_a_acctrajcmd_sg_;
}
inline void PLN_Outputs::set_pln_out_a_acctrajcmd_sg(float value) {
  
  pln_out_a_acctrajcmd_sg_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_a_AccTrajCmd_sg)
}

// sint32 PLN_OUT_is_LongTraj_Replan_Level = 57;
inline void PLN_Outputs::clear_pln_out_is_longtraj_replan_level() {
  pln_out_is_longtraj_replan_level_ = 0;
}
inline ::google::protobuf::int32 PLN_Outputs::pln_out_is_longtraj_replan_level() const {
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_is_LongTraj_Replan_Level)
  return pln_out_is_longtraj_replan_level_;
}
inline void PLN_Outputs::set_pln_out_is_longtraj_replan_level(::google::protobuf::int32 value) {
  
  pln_out_is_longtraj_replan_level_ = value;
  // @@protoc_insertion_point(field_set:ads_pln.PLN_Outputs.PLN_OUT_is_LongTraj_Replan_Level)
}

// .ads_common.HafLonTrajParam PLN_OUT_bus_HafLonTrajParam = 58;
inline bool PLN_Outputs::has_pln_out_bus_haflontrajparam() const {
  return this != internal_default_instance() && pln_out_bus_haflontrajparam_ != NULL;
}
inline const ::ads_common::HafLonTrajParam& PLN_Outputs::_internal_pln_out_bus_haflontrajparam() const {
  return *pln_out_bus_haflontrajparam_;
}
inline const ::ads_common::HafLonTrajParam& PLN_Outputs::pln_out_bus_haflontrajparam() const {
  const ::ads_common::HafLonTrajParam* p = pln_out_bus_haflontrajparam_;
  // @@protoc_insertion_point(field_get:ads_pln.PLN_Outputs.PLN_OUT_bus_HafLonTrajParam)
  return p != NULL ? *p : *reinterpret_cast<const ::ads_common::HafLonTrajParam*>(
      &::ads_common::_HafLonTrajParam_default_instance_);
}
inline ::ads_common::HafLonTrajParam* PLN_Outputs::release_pln_out_bus_haflontrajparam() {
  // @@protoc_insertion_point(field_release:ads_pln.PLN_Outputs.PLN_OUT_bus_HafLonTrajParam)
  
  ::ads_common::HafLonTrajParam* temp = pln_out_bus_haflontrajparam_;
  pln_out_bus_haflontrajparam_ = NULL;
  return temp;
}
inline ::ads_common::HafLonTrajParam* PLN_Outputs::mutable_pln_out_bus_haflontrajparam() {
  
  if (pln_out_bus_haflontrajparam_ == NULL) {
    auto* p = CreateMaybeMessage<::ads_common::HafLonTrajParam>(GetArenaNoVirtual());
    pln_out_bus_haflontrajparam_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ads_pln.PLN_Outputs.PLN_OUT_bus_HafLonTrajParam)
  return pln_out_bus_haflontrajparam_;
}
inline void PLN_Outputs::set_allocated_pln_out_bus_haflontrajparam(::ads_common::HafLonTrajParam* pln_out_bus_haflontrajparam) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pln_out_bus_haflontrajparam_);
  }
  if (pln_out_bus_haflontrajparam) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pln_out_bus_haflontrajparam = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pln_out_bus_haflontrajparam, submessage_arena);
    }
    
  } else {
    
  }
  pln_out_bus_haflontrajparam_ = pln_out_bus_haflontrajparam;
  // @@protoc_insertion_point(field_set_allocated:ads_pln.PLN_Outputs.PLN_OUT_bus_HafLonTrajParam)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ads_pln

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ads_5fpln_2eproto
