// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera_me_lane.proto

#include "camera_me_lane.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_camera_5fme_5flane_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_camera_5fme_5flane_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_MeHeader;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_camera_5fme_5flane_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_MeLane;
}  // namespace protobuf_camera_5fme_5flane_2eproto
namespace camera_me_lane {
namespace proto {
class MeHeaderDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MeHeader>
      _instance;
} _MeHeader_default_instance_;
class MeLaneDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MeLane>
      _instance;
} _MeLane_default_instance_;
class me_frame_laneDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<me_frame_lane>
      _instance;
} _me_frame_lane_default_instance_;
}  // namespace proto
}  // namespace camera_me_lane
namespace protobuf_camera_5fme_5flane_2eproto {
static void InitDefaultsMeHeader() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::camera_me_lane::proto::_MeHeader_default_instance_;
    new (ptr) ::camera_me_lane::proto::MeHeader();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::camera_me_lane::proto::MeHeader::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MeHeader =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMeHeader}, {}};

static void InitDefaultsMeLane() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::camera_me_lane::proto::_MeLane_default_instance_;
    new (ptr) ::camera_me_lane::proto::MeLane();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::camera_me_lane::proto::MeLane::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MeLane =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMeLane}, {}};

static void InitDefaultsme_frame_lane() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::camera_me_lane::proto::_me_frame_lane_default_instance_;
    new (ptr) ::camera_me_lane::proto::me_frame_lane();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::camera_me_lane::proto::me_frame_lane::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_me_frame_lane =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsme_frame_lane}, {
      &protobuf_camera_5fme_5flane_2eproto::scc_info_MeHeader.base,
      &protobuf_camera_5fme_5flane_2eproto::scc_info_MeLane.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_MeHeader.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MeLane.base);
  ::google::protobuf::internal::InitSCC(&scc_info_me_frame_lane.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeHeader, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeHeader, rolling_counter_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeHeader, sensor_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeHeader, obj_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeHeader, line_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeHeader, hazard_num_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, line_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, c0_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, c1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, c2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, c3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, index_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, line_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, start_long_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, end_long_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::MeLane, confidence_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::me_frame_lane, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::me_frame_lane, header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::me_frame_lane, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::camera_me_lane::proto::me_frame_lane, lanes_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::camera_me_lane::proto::MeHeader)},
  { 11, -1, sizeof(::camera_me_lane::proto::MeLane)},
  { 26, -1, sizeof(::camera_me_lane::proto::me_frame_lane)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::camera_me_lane::proto::_MeHeader_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::camera_me_lane::proto::_MeLane_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::camera_me_lane::proto::_me_frame_lane_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "camera_me_lane.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024camera_me_lane.proto\022\024camera_me_lane.p"
      "roto\"\200\001\n\010MeHeader\022\021\n\ttimestamp\030\001 \001(\004\022\027\n\017"
      "rolling_counter\030\002 \001(\r\022\021\n\tsensor_id\030\003 \001(\r"
      "\022\017\n\007obj_num\030\004 \001(\r\022\020\n\010line_num\030\005 \001(\r\022\022\n\nh"
      "azard_num\030\006 \001(\r\"\245\001\n\006MeLane\022\017\n\007line_id\030\001 "
      "\001(\r\022\n\n\002C0\030\002 \001(\001\022\n\n\002C1\030\003 \001(\001\022\n\n\002C2\030\004 \001(\001\022"
      "\n\n\002C3\030\005 \001(\001\022\r\n\005index\030\006 \001(\r\022\021\n\tline_type\030"
      "\007 \001(\r\022\022\n\nstart_long\030\010 \001(\001\022\020\n\010end_long\030\t "
      "\001(\001\022\022\n\nconfidence\030\n \001(\001\"\177\n\rme_frame_lane"
      "\022.\n\006header\030\001 \001(\0132\036.camera_me_lane.proto."
      "MeHeader\022\021\n\ttimestamp\030\002 \001(\004\022+\n\005lanes\030\003 \003"
      "(\0132\034.camera_me_lane.proto.MeLaneb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 480);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "camera_me_lane.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_camera_5fme_5flane_2eproto
namespace camera_me_lane {
namespace proto {

// ===================================================================

void MeHeader::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MeHeader::kTimestampFieldNumber;
const int MeHeader::kRollingCounterFieldNumber;
const int MeHeader::kSensorIdFieldNumber;
const int MeHeader::kObjNumFieldNumber;
const int MeHeader::kLineNumFieldNumber;
const int MeHeader::kHazardNumFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MeHeader::MeHeader()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_camera_5fme_5flane_2eproto::scc_info_MeHeader.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera_me_lane.proto.MeHeader)
}
MeHeader::MeHeader(const MeHeader& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&timestamp_, &from.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&hazard_num_) -
    reinterpret_cast<char*>(&timestamp_)) + sizeof(hazard_num_));
  // @@protoc_insertion_point(copy_constructor:camera_me_lane.proto.MeHeader)
}

void MeHeader::SharedCtor() {
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hazard_num_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(hazard_num_));
}

MeHeader::~MeHeader() {
  // @@protoc_insertion_point(destructor:camera_me_lane.proto.MeHeader)
  SharedDtor();
}

void MeHeader::SharedDtor() {
}

void MeHeader::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MeHeader::descriptor() {
  ::protobuf_camera_5fme_5flane_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_camera_5fme_5flane_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MeHeader& MeHeader::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_camera_5fme_5flane_2eproto::scc_info_MeHeader.base);
  return *internal_default_instance();
}


void MeHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:camera_me_lane.proto.MeHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hazard_num_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(hazard_num_));
  _internal_metadata_.Clear();
}

bool MeHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera_me_lane.proto.MeHeader)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 rolling_counter = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &rolling_counter_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 sensor_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sensor_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 obj_num = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &obj_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 line_num = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &line_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 hazard_num = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &hazard_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera_me_lane.proto.MeHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera_me_lane.proto.MeHeader)
  return false;
#undef DO_
}

void MeHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera_me_lane.proto.MeHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 timestamp = 1;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->timestamp(), output);
  }

  // uint32 rolling_counter = 2;
  if (this->rolling_counter() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->rolling_counter(), output);
  }

  // uint32 sensor_id = 3;
  if (this->sensor_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->sensor_id(), output);
  }

  // uint32 obj_num = 4;
  if (this->obj_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->obj_num(), output);
  }

  // uint32 line_num = 5;
  if (this->line_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->line_num(), output);
  }

  // uint32 hazard_num = 6;
  if (this->hazard_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->hazard_num(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:camera_me_lane.proto.MeHeader)
}

::google::protobuf::uint8* MeHeader::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:camera_me_lane.proto.MeHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 timestamp = 1;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->timestamp(), target);
  }

  // uint32 rolling_counter = 2;
  if (this->rolling_counter() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->rolling_counter(), target);
  }

  // uint32 sensor_id = 3;
  if (this->sensor_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->sensor_id(), target);
  }

  // uint32 obj_num = 4;
  if (this->obj_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->obj_num(), target);
  }

  // uint32 line_num = 5;
  if (this->line_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->line_num(), target);
  }

  // uint32 hazard_num = 6;
  if (this->hazard_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->hazard_num(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:camera_me_lane.proto.MeHeader)
  return target;
}

size_t MeHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera_me_lane.proto.MeHeader)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint64 timestamp = 1;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  // uint32 rolling_counter = 2;
  if (this->rolling_counter() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->rolling_counter());
  }

  // uint32 sensor_id = 3;
  if (this->sensor_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sensor_id());
  }

  // uint32 obj_num = 4;
  if (this->obj_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->obj_num());
  }

  // uint32 line_num = 5;
  if (this->line_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->line_num());
  }

  // uint32 hazard_num = 6;
  if (this->hazard_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->hazard_num());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MeHeader::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera_me_lane.proto.MeHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const MeHeader* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MeHeader>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera_me_lane.proto.MeHeader)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera_me_lane.proto.MeHeader)
    MergeFrom(*source);
  }
}

void MeHeader::MergeFrom(const MeHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera_me_lane.proto.MeHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.rolling_counter() != 0) {
    set_rolling_counter(from.rolling_counter());
  }
  if (from.sensor_id() != 0) {
    set_sensor_id(from.sensor_id());
  }
  if (from.obj_num() != 0) {
    set_obj_num(from.obj_num());
  }
  if (from.line_num() != 0) {
    set_line_num(from.line_num());
  }
  if (from.hazard_num() != 0) {
    set_hazard_num(from.hazard_num());
  }
}

void MeHeader::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera_me_lane.proto.MeHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MeHeader::CopyFrom(const MeHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera_me_lane.proto.MeHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MeHeader::IsInitialized() const {
  return true;
}

void MeHeader::Swap(MeHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MeHeader::InternalSwap(MeHeader* other) {
  using std::swap;
  swap(timestamp_, other->timestamp_);
  swap(rolling_counter_, other->rolling_counter_);
  swap(sensor_id_, other->sensor_id_);
  swap(obj_num_, other->obj_num_);
  swap(line_num_, other->line_num_);
  swap(hazard_num_, other->hazard_num_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MeHeader::GetMetadata() const {
  protobuf_camera_5fme_5flane_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_camera_5fme_5flane_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MeLane::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MeLane::kLineIdFieldNumber;
const int MeLane::kC0FieldNumber;
const int MeLane::kC1FieldNumber;
const int MeLane::kC2FieldNumber;
const int MeLane::kC3FieldNumber;
const int MeLane::kIndexFieldNumber;
const int MeLane::kLineTypeFieldNumber;
const int MeLane::kStartLongFieldNumber;
const int MeLane::kEndLongFieldNumber;
const int MeLane::kConfidenceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MeLane::MeLane()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_camera_5fme_5flane_2eproto::scc_info_MeLane.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera_me_lane.proto.MeLane)
}
MeLane::MeLane(const MeLane& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&c0_, &from.c0_,
    static_cast<size_t>(reinterpret_cast<char*>(&line_type_) -
    reinterpret_cast<char*>(&c0_)) + sizeof(line_type_));
  // @@protoc_insertion_point(copy_constructor:camera_me_lane.proto.MeLane)
}

void MeLane::SharedCtor() {
  ::memset(&c0_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&line_type_) -
      reinterpret_cast<char*>(&c0_)) + sizeof(line_type_));
}

MeLane::~MeLane() {
  // @@protoc_insertion_point(destructor:camera_me_lane.proto.MeLane)
  SharedDtor();
}

void MeLane::SharedDtor() {
}

void MeLane::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MeLane::descriptor() {
  ::protobuf_camera_5fme_5flane_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_camera_5fme_5flane_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MeLane& MeLane::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_camera_5fme_5flane_2eproto::scc_info_MeLane.base);
  return *internal_default_instance();
}


void MeLane::Clear() {
// @@protoc_insertion_point(message_clear_start:camera_me_lane.proto.MeLane)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&c0_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&line_type_) -
      reinterpret_cast<char*>(&c0_)) + sizeof(line_type_));
  _internal_metadata_.Clear();
}

bool MeLane::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera_me_lane.proto.MeLane)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 line_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &line_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double C0 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &c0_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double C1 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &c1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double C2 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &c2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double C3 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &c3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 index = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 line_type = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &line_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double start_long = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(65u /* 65 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &start_long_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double end_long = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(73u /* 73 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &end_long_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double confidence = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(81u /* 81 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &confidence_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera_me_lane.proto.MeLane)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera_me_lane.proto.MeLane)
  return false;
#undef DO_
}

void MeLane::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera_me_lane.proto.MeLane)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 line_id = 1;
  if (this->line_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->line_id(), output);
  }

  // double C0 = 2;
  if (this->c0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->c0(), output);
  }

  // double C1 = 3;
  if (this->c1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->c1(), output);
  }

  // double C2 = 4;
  if (this->c2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->c2(), output);
  }

  // double C3 = 5;
  if (this->c3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->c3(), output);
  }

  // uint32 index = 6;
  if (this->index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->index(), output);
  }

  // uint32 line_type = 7;
  if (this->line_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->line_type(), output);
  }

  // double start_long = 8;
  if (this->start_long() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->start_long(), output);
  }

  // double end_long = 9;
  if (this->end_long() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->end_long(), output);
  }

  // double confidence = 10;
  if (this->confidence() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->confidence(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:camera_me_lane.proto.MeLane)
}

::google::protobuf::uint8* MeLane::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:camera_me_lane.proto.MeLane)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 line_id = 1;
  if (this->line_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->line_id(), target);
  }

  // double C0 = 2;
  if (this->c0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->c0(), target);
  }

  // double C1 = 3;
  if (this->c1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->c1(), target);
  }

  // double C2 = 4;
  if (this->c2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->c2(), target);
  }

  // double C3 = 5;
  if (this->c3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->c3(), target);
  }

  // uint32 index = 6;
  if (this->index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->index(), target);
  }

  // uint32 line_type = 7;
  if (this->line_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->line_type(), target);
  }

  // double start_long = 8;
  if (this->start_long() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->start_long(), target);
  }

  // double end_long = 9;
  if (this->end_long() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->end_long(), target);
  }

  // double confidence = 10;
  if (this->confidence() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->confidence(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:camera_me_lane.proto.MeLane)
  return target;
}

size_t MeLane::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera_me_lane.proto.MeLane)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double C0 = 2;
  if (this->c0() != 0) {
    total_size += 1 + 8;
  }

  // double C1 = 3;
  if (this->c1() != 0) {
    total_size += 1 + 8;
  }

  // uint32 line_id = 1;
  if (this->line_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->line_id());
  }

  // uint32 index = 6;
  if (this->index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->index());
  }

  // double C2 = 4;
  if (this->c2() != 0) {
    total_size += 1 + 8;
  }

  // double C3 = 5;
  if (this->c3() != 0) {
    total_size += 1 + 8;
  }

  // double start_long = 8;
  if (this->start_long() != 0) {
    total_size += 1 + 8;
  }

  // double end_long = 9;
  if (this->end_long() != 0) {
    total_size += 1 + 8;
  }

  // double confidence = 10;
  if (this->confidence() != 0) {
    total_size += 1 + 8;
  }

  // uint32 line_type = 7;
  if (this->line_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->line_type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MeLane::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera_me_lane.proto.MeLane)
  GOOGLE_DCHECK_NE(&from, this);
  const MeLane* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MeLane>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera_me_lane.proto.MeLane)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera_me_lane.proto.MeLane)
    MergeFrom(*source);
  }
}

void MeLane::MergeFrom(const MeLane& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera_me_lane.proto.MeLane)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.c0() != 0) {
    set_c0(from.c0());
  }
  if (from.c1() != 0) {
    set_c1(from.c1());
  }
  if (from.line_id() != 0) {
    set_line_id(from.line_id());
  }
  if (from.index() != 0) {
    set_index(from.index());
  }
  if (from.c2() != 0) {
    set_c2(from.c2());
  }
  if (from.c3() != 0) {
    set_c3(from.c3());
  }
  if (from.start_long() != 0) {
    set_start_long(from.start_long());
  }
  if (from.end_long() != 0) {
    set_end_long(from.end_long());
  }
  if (from.confidence() != 0) {
    set_confidence(from.confidence());
  }
  if (from.line_type() != 0) {
    set_line_type(from.line_type());
  }
}

void MeLane::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera_me_lane.proto.MeLane)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MeLane::CopyFrom(const MeLane& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera_me_lane.proto.MeLane)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MeLane::IsInitialized() const {
  return true;
}

void MeLane::Swap(MeLane* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MeLane::InternalSwap(MeLane* other) {
  using std::swap;
  swap(c0_, other->c0_);
  swap(c1_, other->c1_);
  swap(line_id_, other->line_id_);
  swap(index_, other->index_);
  swap(c2_, other->c2_);
  swap(c3_, other->c3_);
  swap(start_long_, other->start_long_);
  swap(end_long_, other->end_long_);
  swap(confidence_, other->confidence_);
  swap(line_type_, other->line_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MeLane::GetMetadata() const {
  protobuf_camera_5fme_5flane_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_camera_5fme_5flane_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void me_frame_lane::InitAsDefaultInstance() {
  ::camera_me_lane::proto::_me_frame_lane_default_instance_._instance.get_mutable()->header_ = const_cast< ::camera_me_lane::proto::MeHeader*>(
      ::camera_me_lane::proto::MeHeader::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int me_frame_lane::kHeaderFieldNumber;
const int me_frame_lane::kTimestampFieldNumber;
const int me_frame_lane::kLanesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

me_frame_lane::me_frame_lane()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_camera_5fme_5flane_2eproto::scc_info_me_frame_lane.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera_me_lane.proto.me_frame_lane)
}
me_frame_lane::me_frame_lane(const me_frame_lane& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      lanes_(from.lanes_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_header()) {
    header_ = new ::camera_me_lane::proto::MeHeader(*from.header_);
  } else {
    header_ = NULL;
  }
  timestamp_ = from.timestamp_;
  // @@protoc_insertion_point(copy_constructor:camera_me_lane.proto.me_frame_lane)
}

void me_frame_lane::SharedCtor() {
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timestamp_) -
      reinterpret_cast<char*>(&header_)) + sizeof(timestamp_));
}

me_frame_lane::~me_frame_lane() {
  // @@protoc_insertion_point(destructor:camera_me_lane.proto.me_frame_lane)
  SharedDtor();
}

void me_frame_lane::SharedDtor() {
  if (this != internal_default_instance()) delete header_;
}

void me_frame_lane::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* me_frame_lane::descriptor() {
  ::protobuf_camera_5fme_5flane_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_camera_5fme_5flane_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const me_frame_lane& me_frame_lane::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_camera_5fme_5flane_2eproto::scc_info_me_frame_lane.base);
  return *internal_default_instance();
}


void me_frame_lane::Clear() {
// @@protoc_insertion_point(message_clear_start:camera_me_lane.proto.me_frame_lane)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  lanes_.Clear();
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
  timestamp_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool me_frame_lane::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera_me_lane.proto.me_frame_lane)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .camera_me_lane.proto.MeHeader header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 timestamp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .camera_me_lane.proto.MeLane lanes = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_lanes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera_me_lane.proto.me_frame_lane)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera_me_lane.proto.me_frame_lane)
  return false;
#undef DO_
}

void me_frame_lane::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera_me_lane.proto.me_frame_lane)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .camera_me_lane.proto.MeHeader header = 1;
  if (this->has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_header(), output);
  }

  // uint64 timestamp = 2;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->timestamp(), output);
  }

  // repeated .camera_me_lane.proto.MeLane lanes = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->lanes_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->lanes(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:camera_me_lane.proto.me_frame_lane)
}

::google::protobuf::uint8* me_frame_lane::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:camera_me_lane.proto.me_frame_lane)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .camera_me_lane.proto.MeHeader header = 1;
  if (this->has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_header(), deterministic, target);
  }

  // uint64 timestamp = 2;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->timestamp(), target);
  }

  // repeated .camera_me_lane.proto.MeLane lanes = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->lanes_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->lanes(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:camera_me_lane.proto.me_frame_lane)
  return target;
}

size_t me_frame_lane::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera_me_lane.proto.me_frame_lane)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .camera_me_lane.proto.MeLane lanes = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->lanes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->lanes(static_cast<int>(i)));
    }
  }

  // .camera_me_lane.proto.MeHeader header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *header_);
  }

  // uint64 timestamp = 2;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void me_frame_lane::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera_me_lane.proto.me_frame_lane)
  GOOGLE_DCHECK_NE(&from, this);
  const me_frame_lane* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const me_frame_lane>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera_me_lane.proto.me_frame_lane)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera_me_lane.proto.me_frame_lane)
    MergeFrom(*source);
  }
}

void me_frame_lane::MergeFrom(const me_frame_lane& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera_me_lane.proto.me_frame_lane)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  lanes_.MergeFrom(from.lanes_);
  if (from.has_header()) {
    mutable_header()->::camera_me_lane::proto::MeHeader::MergeFrom(from.header());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void me_frame_lane::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera_me_lane.proto.me_frame_lane)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void me_frame_lane::CopyFrom(const me_frame_lane& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera_me_lane.proto.me_frame_lane)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool me_frame_lane::IsInitialized() const {
  return true;
}

void me_frame_lane::Swap(me_frame_lane* other) {
  if (other == this) return;
  InternalSwap(other);
}
void me_frame_lane::InternalSwap(me_frame_lane* other) {
  using std::swap;
  CastToBase(&lanes_)->InternalSwap(CastToBase(&other->lanes_));
  swap(header_, other->header_);
  swap(timestamp_, other->timestamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata me_frame_lane::GetMetadata() const {
  protobuf_camera_5fme_5flane_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_camera_5fme_5flane_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace camera_me_lane
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::camera_me_lane::proto::MeHeader* Arena::CreateMaybeMessage< ::camera_me_lane::proto::MeHeader >(Arena* arena) {
  return Arena::CreateInternal< ::camera_me_lane::proto::MeHeader >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::camera_me_lane::proto::MeLane* Arena::CreateMaybeMessage< ::camera_me_lane::proto::MeLane >(Arena* arena) {
  return Arena::CreateInternal< ::camera_me_lane::proto::MeLane >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::camera_me_lane::proto::me_frame_lane* Arena::CreateMaybeMessage< ::camera_me_lane::proto::me_frame_lane >(Arena* arena) {
  return Arena::CreateInternal< ::camera_me_lane::proto::me_frame_lane >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
