// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radar_srr_fc_fs.proto

#include "radar_srr_fc_fs.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_radar_5fsrr_5ffc_5ffs_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_radar_5fsrr_5ffc_5ffs_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SrrFreeSpace;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_radar_5fsrr_5ffc_5ffs_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SrrHeader;
}  // namespace protobuf_radar_5fsrr_5ffc_5ffs_2eproto
namespace radar_srr_fc_fs {
namespace proto {
class SrrHeaderDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SrrHeader>
      _instance;
} _SrrHeader_default_instance_;
class SrrFreeSpaceDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SrrFreeSpace>
      _instance;
} _SrrFreeSpace_default_instance_;
class srr_fc_frame_fsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<srr_fc_frame_fs>
      _instance;
} _srr_fc_frame_fs_default_instance_;
}  // namespace proto
}  // namespace radar_srr_fc_fs
namespace protobuf_radar_5fsrr_5ffc_5ffs_2eproto {
static void InitDefaultsSrrHeader() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::radar_srr_fc_fs::proto::_SrrHeader_default_instance_;
    new (ptr) ::radar_srr_fc_fs::proto::SrrHeader();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::radar_srr_fc_fs::proto::SrrHeader::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SrrHeader =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSrrHeader}, {}};

static void InitDefaultsSrrFreeSpace() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::radar_srr_fc_fs::proto::_SrrFreeSpace_default_instance_;
    new (ptr) ::radar_srr_fc_fs::proto::SrrFreeSpace();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::radar_srr_fc_fs::proto::SrrFreeSpace::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SrrFreeSpace =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSrrFreeSpace}, {}};

static void InitDefaultssrr_fc_frame_fs() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::radar_srr_fc_fs::proto::_srr_fc_frame_fs_default_instance_;
    new (ptr) ::radar_srr_fc_fs::proto::srr_fc_frame_fs();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::radar_srr_fc_fs::proto::srr_fc_frame_fs::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_srr_fc_frame_fs =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultssrr_fc_frame_fs}, {
      &protobuf_radar_5fsrr_5ffc_5ffs_2eproto::scc_info_SrrHeader.base,
      &protobuf_radar_5fsrr_5ffc_5ffs_2eproto::scc_info_SrrFreeSpace.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SrrHeader.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SrrFreeSpace.base);
  ::google::protobuf::internal::InitSCC(&scc_info_srr_fc_frame_fs.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrHeader, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrHeader, rolling_counter_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrHeader, sensor_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrHeader, obj_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrHeader, line_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrHeader, fs_num_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrFreeSpace, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrFreeSpace, freespace_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrFreeSpace, motion_status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrFreeSpace, distance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::SrrFreeSpace, confidence_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::srr_fc_frame_fs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::srr_fc_frame_fs, header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::srr_fc_frame_fs, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::radar_srr_fc_fs::proto::srr_fc_frame_fs, fs_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::radar_srr_fc_fs::proto::SrrHeader)},
  { 11, -1, sizeof(::radar_srr_fc_fs::proto::SrrFreeSpace)},
  { 20, -1, sizeof(::radar_srr_fc_fs::proto::srr_fc_frame_fs)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::radar_srr_fc_fs::proto::_SrrHeader_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::radar_srr_fc_fs::proto::_SrrFreeSpace_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::radar_srr_fc_fs::proto::_srr_fc_frame_fs_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "radar_srr_fc_fs.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025radar_srr_fc_fs.proto\022\025radar_srr_fc_fs"
      ".proto\"}\n\tSrrHeader\022\021\n\ttimestamp\030\001 \001(\004\022\027"
      "\n\017rolling_counter\030\002 \001(\r\022\021\n\tsensor_id\030\003 \001"
      "(\r\022\017\n\007obj_num\030\004 \001(\r\022\020\n\010line_num\030\005 \001(\r\022\016\n"
      "\006fs_num\030\006 \001(\r\"a\n\014SrrFreeSpace\022\024\n\014freespa"
      "ce_id\030\001 \001(\r\022\025\n\rmotion_status\030\002 \001(\r\022\020\n\010di"
      "stance\030\003 \001(\001\022\022\n\nconfidence\030\004 \001(\001\"\207\001\n\017srr"
      "_fc_frame_fs\0220\n\006header\030\001 \001(\0132 .radar_srr"
      "_fc_fs.proto.SrrHeader\022\021\n\ttimestamp\030\002 \001("
      "\004\022/\n\002fs\030\003 \003(\0132#.radar_srr_fc_fs.proto.Sr"
      "rFreeSpaceb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 418);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "radar_srr_fc_fs.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_radar_5fsrr_5ffc_5ffs_2eproto
namespace radar_srr_fc_fs {
namespace proto {

// ===================================================================

void SrrHeader::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SrrHeader::kTimestampFieldNumber;
const int SrrHeader::kRollingCounterFieldNumber;
const int SrrHeader::kSensorIdFieldNumber;
const int SrrHeader::kObjNumFieldNumber;
const int SrrHeader::kLineNumFieldNumber;
const int SrrHeader::kFsNumFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SrrHeader::SrrHeader()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_radar_5fsrr_5ffc_5ffs_2eproto::scc_info_SrrHeader.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:radar_srr_fc_fs.proto.SrrHeader)
}
SrrHeader::SrrHeader(const SrrHeader& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&timestamp_, &from.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&fs_num_) -
    reinterpret_cast<char*>(&timestamp_)) + sizeof(fs_num_));
  // @@protoc_insertion_point(copy_constructor:radar_srr_fc_fs.proto.SrrHeader)
}

void SrrHeader::SharedCtor() {
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&fs_num_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(fs_num_));
}

SrrHeader::~SrrHeader() {
  // @@protoc_insertion_point(destructor:radar_srr_fc_fs.proto.SrrHeader)
  SharedDtor();
}

void SrrHeader::SharedDtor() {
}

void SrrHeader::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SrrHeader::descriptor() {
  ::protobuf_radar_5fsrr_5ffc_5ffs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_radar_5fsrr_5ffc_5ffs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SrrHeader& SrrHeader::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_radar_5fsrr_5ffc_5ffs_2eproto::scc_info_SrrHeader.base);
  return *internal_default_instance();
}


void SrrHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:radar_srr_fc_fs.proto.SrrHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&fs_num_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(fs_num_));
  _internal_metadata_.Clear();
}

bool SrrHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:radar_srr_fc_fs.proto.SrrHeader)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 rolling_counter = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &rolling_counter_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 sensor_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sensor_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 obj_num = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &obj_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 line_num = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &line_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 fs_num = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &fs_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:radar_srr_fc_fs.proto.SrrHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:radar_srr_fc_fs.proto.SrrHeader)
  return false;
#undef DO_
}

void SrrHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:radar_srr_fc_fs.proto.SrrHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 timestamp = 1;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->timestamp(), output);
  }

  // uint32 rolling_counter = 2;
  if (this->rolling_counter() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->rolling_counter(), output);
  }

  // uint32 sensor_id = 3;
  if (this->sensor_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->sensor_id(), output);
  }

  // uint32 obj_num = 4;
  if (this->obj_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->obj_num(), output);
  }

  // uint32 line_num = 5;
  if (this->line_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->line_num(), output);
  }

  // uint32 fs_num = 6;
  if (this->fs_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->fs_num(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:radar_srr_fc_fs.proto.SrrHeader)
}

::google::protobuf::uint8* SrrHeader::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:radar_srr_fc_fs.proto.SrrHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 timestamp = 1;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->timestamp(), target);
  }

  // uint32 rolling_counter = 2;
  if (this->rolling_counter() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->rolling_counter(), target);
  }

  // uint32 sensor_id = 3;
  if (this->sensor_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->sensor_id(), target);
  }

  // uint32 obj_num = 4;
  if (this->obj_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->obj_num(), target);
  }

  // uint32 line_num = 5;
  if (this->line_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->line_num(), target);
  }

  // uint32 fs_num = 6;
  if (this->fs_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->fs_num(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:radar_srr_fc_fs.proto.SrrHeader)
  return target;
}

size_t SrrHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:radar_srr_fc_fs.proto.SrrHeader)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint64 timestamp = 1;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  // uint32 rolling_counter = 2;
  if (this->rolling_counter() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->rolling_counter());
  }

  // uint32 sensor_id = 3;
  if (this->sensor_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sensor_id());
  }

  // uint32 obj_num = 4;
  if (this->obj_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->obj_num());
  }

  // uint32 line_num = 5;
  if (this->line_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->line_num());
  }

  // uint32 fs_num = 6;
  if (this->fs_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->fs_num());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SrrHeader::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:radar_srr_fc_fs.proto.SrrHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const SrrHeader* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SrrHeader>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:radar_srr_fc_fs.proto.SrrHeader)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:radar_srr_fc_fs.proto.SrrHeader)
    MergeFrom(*source);
  }
}

void SrrHeader::MergeFrom(const SrrHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:radar_srr_fc_fs.proto.SrrHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.rolling_counter() != 0) {
    set_rolling_counter(from.rolling_counter());
  }
  if (from.sensor_id() != 0) {
    set_sensor_id(from.sensor_id());
  }
  if (from.obj_num() != 0) {
    set_obj_num(from.obj_num());
  }
  if (from.line_num() != 0) {
    set_line_num(from.line_num());
  }
  if (from.fs_num() != 0) {
    set_fs_num(from.fs_num());
  }
}

void SrrHeader::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:radar_srr_fc_fs.proto.SrrHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SrrHeader::CopyFrom(const SrrHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:radar_srr_fc_fs.proto.SrrHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SrrHeader::IsInitialized() const {
  return true;
}

void SrrHeader::Swap(SrrHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SrrHeader::InternalSwap(SrrHeader* other) {
  using std::swap;
  swap(timestamp_, other->timestamp_);
  swap(rolling_counter_, other->rolling_counter_);
  swap(sensor_id_, other->sensor_id_);
  swap(obj_num_, other->obj_num_);
  swap(line_num_, other->line_num_);
  swap(fs_num_, other->fs_num_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SrrHeader::GetMetadata() const {
  protobuf_radar_5fsrr_5ffc_5ffs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_radar_5fsrr_5ffc_5ffs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SrrFreeSpace::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SrrFreeSpace::kFreespaceIdFieldNumber;
const int SrrFreeSpace::kMotionStatusFieldNumber;
const int SrrFreeSpace::kDistanceFieldNumber;
const int SrrFreeSpace::kConfidenceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SrrFreeSpace::SrrFreeSpace()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_radar_5fsrr_5ffc_5ffs_2eproto::scc_info_SrrFreeSpace.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:radar_srr_fc_fs.proto.SrrFreeSpace)
}
SrrFreeSpace::SrrFreeSpace(const SrrFreeSpace& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&freespace_id_, &from.freespace_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&confidence_) -
    reinterpret_cast<char*>(&freespace_id_)) + sizeof(confidence_));
  // @@protoc_insertion_point(copy_constructor:radar_srr_fc_fs.proto.SrrFreeSpace)
}

void SrrFreeSpace::SharedCtor() {
  ::memset(&freespace_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&confidence_) -
      reinterpret_cast<char*>(&freespace_id_)) + sizeof(confidence_));
}

SrrFreeSpace::~SrrFreeSpace() {
  // @@protoc_insertion_point(destructor:radar_srr_fc_fs.proto.SrrFreeSpace)
  SharedDtor();
}

void SrrFreeSpace::SharedDtor() {
}

void SrrFreeSpace::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SrrFreeSpace::descriptor() {
  ::protobuf_radar_5fsrr_5ffc_5ffs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_radar_5fsrr_5ffc_5ffs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SrrFreeSpace& SrrFreeSpace::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_radar_5fsrr_5ffc_5ffs_2eproto::scc_info_SrrFreeSpace.base);
  return *internal_default_instance();
}


void SrrFreeSpace::Clear() {
// @@protoc_insertion_point(message_clear_start:radar_srr_fc_fs.proto.SrrFreeSpace)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&freespace_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&confidence_) -
      reinterpret_cast<char*>(&freespace_id_)) + sizeof(confidence_));
  _internal_metadata_.Clear();
}

bool SrrFreeSpace::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:radar_srr_fc_fs.proto.SrrFreeSpace)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 freespace_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &freespace_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 motion_status = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &motion_status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double distance = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &distance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double confidence = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &confidence_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:radar_srr_fc_fs.proto.SrrFreeSpace)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:radar_srr_fc_fs.proto.SrrFreeSpace)
  return false;
#undef DO_
}

void SrrFreeSpace::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:radar_srr_fc_fs.proto.SrrFreeSpace)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 freespace_id = 1;
  if (this->freespace_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->freespace_id(), output);
  }

  // uint32 motion_status = 2;
  if (this->motion_status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->motion_status(), output);
  }

  // double distance = 3;
  if (this->distance() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->distance(), output);
  }

  // double confidence = 4;
  if (this->confidence() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->confidence(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:radar_srr_fc_fs.proto.SrrFreeSpace)
}

::google::protobuf::uint8* SrrFreeSpace::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:radar_srr_fc_fs.proto.SrrFreeSpace)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 freespace_id = 1;
  if (this->freespace_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->freespace_id(), target);
  }

  // uint32 motion_status = 2;
  if (this->motion_status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->motion_status(), target);
  }

  // double distance = 3;
  if (this->distance() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->distance(), target);
  }

  // double confidence = 4;
  if (this->confidence() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->confidence(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:radar_srr_fc_fs.proto.SrrFreeSpace)
  return target;
}

size_t SrrFreeSpace::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:radar_srr_fc_fs.proto.SrrFreeSpace)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 freespace_id = 1;
  if (this->freespace_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->freespace_id());
  }

  // uint32 motion_status = 2;
  if (this->motion_status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->motion_status());
  }

  // double distance = 3;
  if (this->distance() != 0) {
    total_size += 1 + 8;
  }

  // double confidence = 4;
  if (this->confidence() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SrrFreeSpace::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:radar_srr_fc_fs.proto.SrrFreeSpace)
  GOOGLE_DCHECK_NE(&from, this);
  const SrrFreeSpace* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SrrFreeSpace>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:radar_srr_fc_fs.proto.SrrFreeSpace)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:radar_srr_fc_fs.proto.SrrFreeSpace)
    MergeFrom(*source);
  }
}

void SrrFreeSpace::MergeFrom(const SrrFreeSpace& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:radar_srr_fc_fs.proto.SrrFreeSpace)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.freespace_id() != 0) {
    set_freespace_id(from.freespace_id());
  }
  if (from.motion_status() != 0) {
    set_motion_status(from.motion_status());
  }
  if (from.distance() != 0) {
    set_distance(from.distance());
  }
  if (from.confidence() != 0) {
    set_confidence(from.confidence());
  }
}

void SrrFreeSpace::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:radar_srr_fc_fs.proto.SrrFreeSpace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SrrFreeSpace::CopyFrom(const SrrFreeSpace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:radar_srr_fc_fs.proto.SrrFreeSpace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SrrFreeSpace::IsInitialized() const {
  return true;
}

void SrrFreeSpace::Swap(SrrFreeSpace* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SrrFreeSpace::InternalSwap(SrrFreeSpace* other) {
  using std::swap;
  swap(freespace_id_, other->freespace_id_);
  swap(motion_status_, other->motion_status_);
  swap(distance_, other->distance_);
  swap(confidence_, other->confidence_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SrrFreeSpace::GetMetadata() const {
  protobuf_radar_5fsrr_5ffc_5ffs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_radar_5fsrr_5ffc_5ffs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void srr_fc_frame_fs::InitAsDefaultInstance() {
  ::radar_srr_fc_fs::proto::_srr_fc_frame_fs_default_instance_._instance.get_mutable()->header_ = const_cast< ::radar_srr_fc_fs::proto::SrrHeader*>(
      ::radar_srr_fc_fs::proto::SrrHeader::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int srr_fc_frame_fs::kHeaderFieldNumber;
const int srr_fc_frame_fs::kTimestampFieldNumber;
const int srr_fc_frame_fs::kFsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

srr_fc_frame_fs::srr_fc_frame_fs()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_radar_5fsrr_5ffc_5ffs_2eproto::scc_info_srr_fc_frame_fs.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:radar_srr_fc_fs.proto.srr_fc_frame_fs)
}
srr_fc_frame_fs::srr_fc_frame_fs(const srr_fc_frame_fs& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      fs_(from.fs_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_header()) {
    header_ = new ::radar_srr_fc_fs::proto::SrrHeader(*from.header_);
  } else {
    header_ = NULL;
  }
  timestamp_ = from.timestamp_;
  // @@protoc_insertion_point(copy_constructor:radar_srr_fc_fs.proto.srr_fc_frame_fs)
}

void srr_fc_frame_fs::SharedCtor() {
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timestamp_) -
      reinterpret_cast<char*>(&header_)) + sizeof(timestamp_));
}

srr_fc_frame_fs::~srr_fc_frame_fs() {
  // @@protoc_insertion_point(destructor:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  SharedDtor();
}

void srr_fc_frame_fs::SharedDtor() {
  if (this != internal_default_instance()) delete header_;
}

void srr_fc_frame_fs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* srr_fc_frame_fs::descriptor() {
  ::protobuf_radar_5fsrr_5ffc_5ffs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_radar_5fsrr_5ffc_5ffs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const srr_fc_frame_fs& srr_fc_frame_fs::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_radar_5fsrr_5ffc_5ffs_2eproto::scc_info_srr_fc_frame_fs.base);
  return *internal_default_instance();
}


void srr_fc_frame_fs::Clear() {
// @@protoc_insertion_point(message_clear_start:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fs_.Clear();
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
  timestamp_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool srr_fc_frame_fs::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .radar_srr_fc_fs.proto.SrrHeader header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 timestamp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .radar_srr_fc_fs.proto.SrrFreeSpace fs = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_fs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  return false;
#undef DO_
}

void srr_fc_frame_fs::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .radar_srr_fc_fs.proto.SrrHeader header = 1;
  if (this->has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_header(), output);
  }

  // uint64 timestamp = 2;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->timestamp(), output);
  }

  // repeated .radar_srr_fc_fs.proto.SrrFreeSpace fs = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->fs_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->fs(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:radar_srr_fc_fs.proto.srr_fc_frame_fs)
}

::google::protobuf::uint8* srr_fc_frame_fs::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .radar_srr_fc_fs.proto.SrrHeader header = 1;
  if (this->has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_header(), deterministic, target);
  }

  // uint64 timestamp = 2;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->timestamp(), target);
  }

  // repeated .radar_srr_fc_fs.proto.SrrFreeSpace fs = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->fs_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->fs(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  return target;
}

size_t srr_fc_frame_fs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .radar_srr_fc_fs.proto.SrrFreeSpace fs = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->fs_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->fs(static_cast<int>(i)));
    }
  }

  // .radar_srr_fc_fs.proto.SrrHeader header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *header_);
  }

  // uint64 timestamp = 2;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void srr_fc_frame_fs::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  GOOGLE_DCHECK_NE(&from, this);
  const srr_fc_frame_fs* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const srr_fc_frame_fs>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:radar_srr_fc_fs.proto.srr_fc_frame_fs)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:radar_srr_fc_fs.proto.srr_fc_frame_fs)
    MergeFrom(*source);
  }
}

void srr_fc_frame_fs::MergeFrom(const srr_fc_frame_fs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  fs_.MergeFrom(from.fs_);
  if (from.has_header()) {
    mutable_header()->::radar_srr_fc_fs::proto::SrrHeader::MergeFrom(from.header());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void srr_fc_frame_fs::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void srr_fc_frame_fs::CopyFrom(const srr_fc_frame_fs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:radar_srr_fc_fs.proto.srr_fc_frame_fs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool srr_fc_frame_fs::IsInitialized() const {
  return true;
}

void srr_fc_frame_fs::Swap(srr_fc_frame_fs* other) {
  if (other == this) return;
  InternalSwap(other);
}
void srr_fc_frame_fs::InternalSwap(srr_fc_frame_fs* other) {
  using std::swap;
  CastToBase(&fs_)->InternalSwap(CastToBase(&other->fs_));
  swap(header_, other->header_);
  swap(timestamp_, other->timestamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata srr_fc_frame_fs::GetMetadata() const {
  protobuf_radar_5fsrr_5ffc_5ffs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_radar_5fsrr_5ffc_5ffs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace radar_srr_fc_fs
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::radar_srr_fc_fs::proto::SrrHeader* Arena::CreateMaybeMessage< ::radar_srr_fc_fs::proto::SrrHeader >(Arena* arena) {
  return Arena::CreateInternal< ::radar_srr_fc_fs::proto::SrrHeader >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::radar_srr_fc_fs::proto::SrrFreeSpace* Arena::CreateMaybeMessage< ::radar_srr_fc_fs::proto::SrrFreeSpace >(Arena* arena) {
  return Arena::CreateInternal< ::radar_srr_fc_fs::proto::SrrFreeSpace >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::radar_srr_fc_fs::proto::srr_fc_frame_fs* Arena::CreateMaybeMessage< ::radar_srr_fc_fs::proto::srr_fc_frame_fs >(Arena* arena) {
  return Arena::CreateInternal< ::radar_srr_fc_fs::proto::srr_fc_frame_fs >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
